org   = Organization.find(4)
event = Event.find_by(slug: "minneapolis-pancakes-booze-art-show")
raise "Event not found!" if event.nil?
raise "Event is not live!" unless event.is_live
artists_app = event.vendor_applications.find_by(name: "Artists")
raise "Artists VendorApplication not found!" if artists_app.nil?

puts "Org: #{org.id} — #{org.name}"
puts "Event: #{event.id} — #{event.title} (live: #{event.is_live})"
puts "Artists app: #{artists_app.id}"

Registration.skip_callback(:create, :after, :send_confirmation_email)
Registration.skip_callback(:update, :after, :send_status_update_email)
puts "Email callbacks disabled."

invited_emails = %w[
  0shua.jjc@gmail.com
  30crowsneststudio@gmail.com
  a.richards1996@outlook.com
  aaronkupcho@yahoo.com
  aartsofwinter@gmail.com
  abbyillustrations@gmail.com
  abbysanders444@gmail.com
  abelachandlery@gmail.com
  abigailengleart@gmail.com
  abstract.acosta@gmail.com
  acg.llc09@gmail.com
  acoxmn@gmail.com
  ad.fishay@gmail.com
  adahl122424@gmail.com
  adam@burlesquedesign.com
  adamfenenga@gmail.com
  admin@scorzelliart.com
  agooart@gmail.com
  ahbtheshadow@gmail.com
  ahorwitz20@gmail.com
  aimatfriesen@gmail.com
  aimee.soltys@gmail.com
  ajan0033@hotmail.com
  alanmjin@gmail.com
  aldonahum93@hotmail.com
  alex.n.moros@live.com
  alex@purplenikon.com
  alexisjohnsonart@gmail.com
  alihilgers35@gmail.com
  alincolnsoft@gmail.com
  aliyawatson@live.com
  allisonwitz@gmail.com
  alphasio0ne@gmail.com
  alyshacolberg@hotmail.com
  alyssapstormes@gmail.com
  amandaboerger22@gmail.com
  amandabushere@gmail.com
  amandamkern9@gmail.com
  amanijcreates@gmail.com
  amberpaints4u@gmail.com
  ambiguous922@yahoo.com
  amy.irene.engler@gmail.com
  amyclark9218@comcast.net
  anabug@gmail.com
  anastasiazabelceramics@gmail.com
  anderson.tad.mn@gmail.com
  andrew.lopez@pezigns.com
  andrewsandberg@comcast.net
  androssland024@gmail.com
  andybrooklynlandy@gmail.com
  andykistner@yahoo.com
  ang093071@gmail.com
  angelamarie133@gmail.com
  angelameyerart@gmail.com
  ann.petermeier@target.com
  anna@weforart.com
  anna_olver@yahoo.com
  annabombb26@yahoo.com
  annacleo101799@yahoo.com
  annagcc95@gmail.com
  annaruok@msn.com
  anomaly394323@yahoo.com
  anotherbuddha@gmail.com
  anton@antonsartworks.com
  arc_war@msn.com
  arcane.rachel@gmail.com
  arelirios90@gmail.com
  art@johnstrouf.com
  artanddesignally@gmail.com
  artbyalexnarva@gmail.com
  artbychum@gmail.com
  artbyjdm@gmail.com
  artbywendymarie@gmail.com
  artistbuilt@yahoo.com
  artistdalelewis@gmail.com
  artisticrenaissancellc@gmail.com
  artistrace90@gmail.com
  artistsholo@gmail.com
  artoconnell@outlook.com
  artscorpiorising@gmail.com
  artxjeanluc@gmail.com
  arvin@deadchannels.tv
  arway2012@gmail.com
  as-is@myself.com
  ashbrama99@gmail.com
  ashleylwiermaa@gmail.com
  ashleyschroepferstore@gmail.com
  ashlie.e.paulson@gmail.com
  ashtonhall96@gmail.com
  asia@billyturner.com
  asoydara@gmail.com
  aspect.midwest@gmail.com
  astralchemy@gmail.com
  atomictommy1@hotmail.com
  aubreyshervheim@gmail.com
  audrey.hj.hong@gmail.com
  audreymarieroach@gmail.com
  austinodomgraphics@gmail.com
  autumnkayatchison@gmail.com
  averyshotyou@gmail.com
  aw_design@rocketmail.com
  axelsunstrom@gmail.com
  azl_777@yahoo.com
  bahamab123@gmail.com
  baku_brian@bakubrian.com
  bambikhanart@gmail.com
  barbrabloy@gmail.com
  beansandbologna@yahoo.com
  beautifulbones13@yahoo.com
  bellasmind222@gmail.com
  bellatoso@gmail.com
  benard.dexter@gmail.com
  berry.holz@gmail.com
  binyjsdacoolest@gmail.com
  black23olive@gmail.com
  blackcoffintattoo@gmail.com
  blackhistoryartistmovemeant@gmail.com
  blackqueen1997@icloud.com
  blake@blakerasmussen.com
  blauren711@gmail.com
  blembi474@gmail.com
  bluehighwayroadart@gmail.com
  blurberrybuzz@gmail.com
  boden.a.k.o@gmail.com
  bonesvtg@gmail.com
  booking@tanaostman.com
  bouka_bedouine@hotmail.fr
  bradleyfritz2002@yahoo.com
  brandon.dyer711@gmail.com
  brandoncole217@hotmail.com
  breannarhodesart@gmail.com
  breatheeasycandleco@gmail.com
  brendersartoo@gmail.com
  brett.whitacre@gmail.com
  briandaviddowns@hotmail.com
  briandefferding@gmail.com
  briannagaughan@gmail.com
  brindleclyde@yahoo.com
  brittanywong06@gmail.com
  brookebot5000@aol.com
  brothersofpanama@gmail.com
  browningj2008@gmail.com
  brutylrubber@gmail.com
  bryangodfrey228@yahoo.com
  bunkema@gmail.com
  bwillusdesigns@gmail.com
  c.n.otterness@gmail.com
  cabe.crowley1985@gmail.com
  caitiesart@gmail.com
  calebvhenkelman@gmail.com
  calvinlinders1@gmail.com
  cambriacrawford@gmail.com
  carissarand@gmail.com
  carol.ledoux@comcast.net
  carolyndrohner@yahoo.com
  carrieedahlquist@gmail.com
  caryshouse@comcast.net
  cassandra.nordeng@gmail.com
  cassandrajaneleroy@gmail.com
  cassiedircz7@hotmail.com
  caswarrenart@gmail.com
  catatoniccouch@gmail.com
  cayla.vickers@gmail.com
  cbphotos1@yahoo.com
  cbrophoto@gmail.com
  cedartop1976@gmail.com
  celiastudios@gmail.com
  celium.bound@gmail.com
  celticpanther25@gmail.com
  centered.stone.designs@gmail.com
  cerviidae@gmail.com
  chadhambright@gmail.com
  charlesdcooper36@gmail.com
  chase@theagatedude.com
  chelseabaert@gmail.com
  chena.stephanie@gmail.com
  chickenbonebaby@gmail.com
  chiikwezensphoenixheadbird@gmail.com
  chiraqthrowback@gmail.com
  chloe.rupprecht@gmail.com
  choleannduranstudios@gmail.com
  chris@blueghoul.com
  chrisjweiss@hotmail.com
  christyrkirk@gmail.com
  chroma.xone1@gmail.com
  cicero@phynixfire.com
  cindy.a.berg@gmail.com
  cindy@thebeautyop.com
  cinematicrhythmatics@gmail.com
  circlebackstudios@gmail.com
  ciriacovera92@gmail.com
  ciyana.johnson@naturallynatureco.com
  claiborneje@gmail.com
  clairefoster@gmail.com
  claritylust@gmail.com
  claybrookart@gmail.com
  clayr@letskeepingcreating.com
  clayt151@umn.edu
  cloudedmoon75@gmail.com
  clydevalentine@gmail.com
  cmrutledgetattoos@gmail.com
  cobileejwest@gmail.com
  cody.dudgeon.mn@gmail.com
  cogitoprints@gmail.com
  colby.kochmann@gmail.com
  colleen@morganphotography.biz
  connect@silentfox.studio
  constant_creator@yahoo.com
  contact@mxnphoto.com
  contactsafihenna@gmail.com
  corbuie@gmail.com
  corey@myinvisiblefriends.com
  corrina.snider@gmail.com
  costellokelly@hotmail.com
  crackedmoonartistry@gmail.com
  cranialindustries@gmail.com
  creador72@hotmail.com
  creationistprime@gmail.com
  creations21590@gmail.com
  creative.aspen.art@gmail.com
  creativecarewigs@gmail.com
  creativenativebeading@gmail.com
  creatureclaycompany@gmail.com
  cristnick19@gmail.com
  crownshep@crownthewriter.com
  crsw2126@gmail.com
  crystal.ieshia@gmail.com
  crystal.sokuu@gmail.com
  curskipics@gmail.com
  customerservice@artisticrenaissance.com
  cwentzelart@gmail.com
  dahlinb@my.normandale.edu
  dalaynidraws@gmail.com
  damautoart7@gmail.com
  damonrwl@gmail.com
  dan.souligny@frnku.com
  danabonnie@gmail.com
  danal@zmsch.k12.mn.us
  danidetuncq@gmail.com
  daniel.hedstrom.jr@outlook.com
  danielmheinlein@gmail.com
  dannyampersand@gmail.com
  darkalleyspecialeffects@gmail.com
  darkossphere@yahoo.com
  darrellhagan@yahoo.com
  davi0078@yahoo.com
  david.benjamin.miller@gmail.com
  david.p.quady@gmail.com
  dbrandt4235@gmail.com
  deadseriousdesigns@gmail.com
  deanurevig@gmail.com
  dearestkim.c@gmail.com
  deck.cp@gmail.com
  delafuente.leila@gmail.com
  denisejordanartmn@gmail.com
  dennykir@outlook.com
  desiray_weaver@hotmail.com
  desiree.schwab20@gmail.com
  dhomick218@gmail.com
  di3d311@yahoo.com
  diamond.barton@outlook.com
  diamondbarksdale35@gmail.com
  diana13088@gmail.com
  dierksartwork@gmail.com
  dinofacepaint@gmail.com
  dionsarahm@gmail.com
  dizzytheartist@afrodisiacarts.com
  djnperko@gmail.com
  doodlezook@yahoo.com
  dove.salvatierra@gmail.com
  dr.lollipopmd@gmail.com
  dr.retta@sharabaked.com
  dragontim2007@yahoo.com
  drewdavid262016@gmail.com
  drhiannon95@yahoo.com
  dsgriego@hotmail.com
  duelvisiontv@yahoo.com
  dugturterpensten@gmail.com
  dyson.sphere.power@gmail.com
  e.macmillan42@gmail.com
  earthb3394@gmail.com
  ebechtel84@gmail.com
  eclark10990@gmail.com
  edie@weirdartmpls.com
  ekovapoops@outlook.com
  ekvalker@gmail.com
  eleanor.giese@gmail.com
  eleanorest@gmail.com
  elguillermo2014@gmail.com
  elise@bonnes.com
  eliseojohndavilajr@gmail.com
  elktech2010@gmail.com
  elle.rhodes@gmail.com
  ellebeegallery@gmail.com
  ellikut@gmail.com
  elouisedesigns.co@gmail.com
  eluedke247@gmail.com
  email@richardabraham.com
  embracingfaces@gmail.com
  emileepc1@gmail.com
  emily.claire.cobb@gmail.com
  emilyannabierbrauer@gmail.com
  emilydoespainting@gmail.com
  emilyglennart@gmail.com
  emml.smallgoods@gmail.com
  emrykjensen@gmail.com
  endxnes@gmail.com
  energyjunctions@gmail.com
  enjorningwild@gmail.com
  enriquedraws@gmail.com
  enviro_mgr@hotmail.com
  erika.gare@outlook.com
  erinjewett6@gmail.com
  erinriley2000@gmail.com
  esnodgress23@gmail.com
  exishentialcrisis@gmail.com
  expression1998@gmail.com
  fabledferns@gmail.com
  facemeporfavor@gmail.com
  faithfarrell@gmail.com
  farnam.futureshock@gmail.com
  ferraya42@gmail.com
  fetherblack@gmail.com
  feven.ayana@gmail.com
  fheinasuo@gmail.com
  fioarti1@gmail.com
  flipp999@gmail.com
  floralmorgue@gmail.com
  flozenmotion@gmail.com
  fluid.creations444@gmail.com
  fondalacey@yahoo.com
  footnow@gmail.com
  foxy@foxyfoundry.com
  frotasticdivas@gmail.com
  funmibanjoko123@gmail.com
  gabe.vogler.1@gmail.com
  gable044@gmail.com
  galaingram34@gmail.com
  gardengro@gmail.com
  geekchictique@gmail.com
  gena.cohen44@gmail.com
  gennygengen@gmail.com
  geodesicmusic@gmail.com
  getme2.mg@gmail.com
  ghosttabbycreations@gmail.com
  ghpaulline44@gmail.com
  giliane.e.mansfeldt@gmail.com
  gilligone@gmail.com
  ginakgerm@yahoo.com
  glassbynate@gmail.com
  gnarlynewty@gmail.com
  goanaglee2019@gmail.com
  gonzalez.diego3@outlook.com
  gonzalez1@grinnell.edu
  goreckistudio@gmail.com
  gorepump@gmail.com
  grace@sassysealart.com
  gracebray@gmail.com
  gracehedtke@gmail.com
  graphite57701@gmail.com
  grayman2776@gmail.com
  grimm.andrea2012@gmail.com
  gustafson.sydne@yahoo.com
  halcyoninkmn@gmail.com
  hallerossart@gmail.com
  hannahbfarrell@gmail.com
  hannahcordes91@gmail.com
  hannahfrickart@gmail.com
  hannahhoughton@gmail.com
  harleygorman.art@gmail.com
  harrimac001@gmail.com
  harrisonrund23@gmail.com
  harutzora@gmail.com
  hceustis@gmail.com
  hdefran@aol.com
  heatherlawrenz@gmail.com
  heathler1@gmail.com
  heatrich79@gmail.com
  heffelfingercedar@gmail.com
  hello@eliandink.com
  hello@fittonia.co
  hello@giftywrap.com
  hi@byruex.com
  hiimderrekgarfield@gmail.com
  hilson.arts@gmail.com
  hlp27206@gmail.com
  holliroseart@gmail.com
  holly@findisms.com
  hollyhillman418@gmail.com
  holtzallison.the@gmail.com
  hometreearts@gmail.com
  hyphaedesigns@gmail.com
  iamsprout@me.com
  ichooseamazing@gmail.com
  igirlscene@gmail.com
  igk1472@gmail.com
  iimanjlai@gmail.com
  indigosunjewelry@gmail.com
  info@edwardlovephotography.com
  info@shawnmcnulty.com
  info@woolendesignart.com
  ini@technologist.computer
  inkerandthinker@gmail.com
  iovin006@umn.edu
  ironhouseart1@gmail.com
  isabelleshervheim@gmail.com
  isimudzeal@yahoo.com
  itsharpycraft@gmail.com
  iyonnaimani@gmail.com
  izzi.hollands@gmail.com
  j.covey@live.com
  j.erickson82@gmail.com
  j.redshaw10@gmail.com
  jaacqueeeeline@gmail.com
  jaali.griffin@gmail.com
  jackie_marie_soens@yahoo.com
  jacqueesec@gmail.com
  jacqueline.athmann@gmail.com
  jake.balch.design@gmail.com
  jamelahcooper@yahoo.com
  jamespwenner@gmail.com
  jamiduluth@gmail.com
  jamiein@hotmail.com
  jamieleecapps@gmail.com
  jamieowensart@gmail.com
  janeamber2001@icloud.com
  janna.c.roloff@gmail.com
  jarrenpdean@gmail.com
  jasmin.os93@gmail.com
  jason@suprachic.com
  jasonsdavis.art@gmail.com
  jasonumentumart@gmail.com
  jastamm@mainsl.com
  jatuma533@gmail.com
  jbomb0000@yahoo.com
  jccanoeten@gmail.com
  jdespen@gmail.com
  jeanniemarieart@gmail.com
  jeffreyisham@gmail.com
  jeffreywjensen76@gmail.com
  jellybean062090@gmail.com
  jennalawton@gmail.com
  jenniepoppie@gmail.com
  jenniferdsandquist@gmail.com
  jennxangell@gmail.com
  jesercize@gmail.com
  jessedlang@gmail.com
  jessegantenbein@gmail.com
  jessegreenhagen@yahoo.com
  jessica.meeksart@gmail.com
  jessica_pendzimas@hotmail.com
  jessicabarnd527@gmail.com
  jessicahalgunseth@yahoo.com
  jessicasund123@gmail.com
  jessie42patterson@gmail.com
  jetblackcrafts@gmail.com
  jewelrysamy@gmail.com
  jewelsdagirl@yahoo.com
  jezebel@jezebelpride.com
  jfcarlson713@gmail.com
  jfstreeter@gmail.com
  jhax@chaosandquirk.art
  jiapark50@gmail.com
  jiayi6120@gmail.com
  jkarenannies@gmail.com
  jlorentzen19@gmail.com
  jlprill78@gmail.com
  jlshoemake@gmail.com
  jlsipova@gmail.com
  jmccord28@yahoo.com
  jmjchungahenna@gmail.com
  jml.gray@hotmail.com
  jmulcahydesign@gmail.com
  jnawro758@gmail.com
  joe.holzhausen@gmail.com
  joemarxen@gmail.com
  johannasmithart@gmail.com
  johnson.ronald.keith@gmail.com
  jojamamida@gmail.com
  jone1831@gmail.com
  jonk0329@gmail.com
  jonnyfromchicago@gmail.com
  jooddart@gmail.com
  jordan@arcservices.pro
  josephine@josephineeverett.com
  josettephx@yahoo.com
  josh.batterson@hotmail.com
  josh.jolly@yahoo.com
  joshfay13@gmail.com
  joshjjohnson95@gmail.com
  jrygura@gmail.com
  jsamsonlaw@gmail.com
  jsanderson5900@gmail.com
  julianeubauer95@gmail.com
  juliannaweigle@gmail.com
  julie.blakeney@gmail.com
  julie.gustafson16@icloud.com
  julief92@aol.com
  julissamarie1120@gmail.com
  juniperteeth@gmail.com
  justinstrom@comcast.net
  juvland.jacqueline@gmail.com
  jw2503is@gmail.com
  k.kelsey.4@gmail.com
  kachowkreations@gmail.com
  kaichai444@gmail.com
  kailmax1214@gmail.com
  kaitlyn.lafferty21996@gmail.com
  kaiwalsh27@gmail.com
  kaldrichmn@gmail.com
  kangasisaac@gmail.com
  kaoleethao@innerswirl.com
  kaponoasuncion@gmail.com
  kappps@hotmail.com
  kararwillis@hotmail.com
  karen.emory.kelly@gmail.com
  karenfultz@live.com
  karenkamrad@gmail.com
  karenobryan@gmail.com
  kariannsky@gmail.com
  kaseyrobinson.visuals@gmail.com
  kateurmann@gmail.com
  katherine.a.young@hotmail.com
  katieanderson2001@yahoo.com
  kay.ringler@gmail.com
  kay@cultureofvibes.com
  kaylahalberg@gmail.com
  kearappoldart@gmail.com
  keariathomsoncochran@gmail.com
  keelipobrien@gmail.com
  keggluneq@gmail.com
  keithart@ymail.com
  kelly@crayonkelly.com
  kellyariyon@gmail.com
  kelseydgonzales@gmail.com
  kelseymwenberg@gmail.com
  kenannwill@gmail.com
  kennedysimpson.design@gmail.com
  kenwellsart@gmail.com
  kenzidonaldsonphoto@gmail.com
  kevinmhb22@gmail.com
  kfrank7680@gmail.com
  kgener195@gmail.com
  kgunn519@gmail.com
  kiara.jackson007@gmail.com
  kidkippo@gmail.com
  kiiadams11@gmail.com
  kimtruedson@gmail.com
  kingbullimages@gmail.com
  kirchner.jamie@gmail.com
  kittyjkremer@gmail.com
  kjerstigoodrich@yahoo.com
  kjmedenwaldt@gmail.com
  klegstada@hotmail.com
  kmcornet@gmail.com
  kmelody227@gmail.com
  krazykara.herring1@gmail.com
  kreativekeezy@gmail.com
  krischarlestonnn@gmail.com
  kristinalloyd@mac.com
  krystalbartlowe@gmail.com
  kuriositiesbykat@gmail.com
  kyleand@hotmail.com
  kyleechr6@gmail.com
  kylejheger@gmail.com
  kylelbernier@outlook.com
  kyliedegrote@gmail.com
  la_hanson@outlook.com
  ladyindigo2@gmail.com
  lafephotography@gmail.com
  lanabosak@gmail.com
  landrae37@gmail.com
  larskrystad@gmail.com
  laskey298@gmail.com
  latherwithloveco@gmail.com
  laura.geiselman@gmail.com
  laurabergren@comcast.net
  laure115@umn.edu
  lavendartdesign@gmail.com
  lavenderxsunshine@gmail.com
  ldiego505@gmail.com
  leahwestlund@icloud.com
  leesheeloops@gmail.com
  leighbauer25@gmail.com
  leilani.schuppan@gmail.com
  levishall38@gmail.com
  lggonzo490@gmail.com
  lilivsdraws@gmail.com
  limpiodesigns@gmail.com
  lindgrek@augsburg.edu
  lindsedwards@gmail.com
  lissakarpeh@gmail.com
  litdistribution@gmail.com
  liverdude888@gmail.com
  lizannewolf@yahoo.com
  lizsnively@aol.com
  lizzyblu7@gmail.com
  lizzyoman666@gmail.com
  lmarie655321@gmail.com
  lmvcraftllc@gmail.com
  loosingcourtney@gmail.com
  loricecicela@comcast.net
  louisrzurn@icloud.com
  loveizcreations@gmail.com
  lowendt45@gmail.com
  lplowman@live.com
  luchos.ink@gmail.com
  lucy.l.dahl@gmail.com
  lucycliff@gmail.com
  lukascarlsonartist@gmail.com
  lvdakes@gmail.com
  lydia.catone@gopuff.com
  lynaea80@gmail.com
  lyquid1@hotmail.com
  lyssasimmons@gmail.com
  m.jaynie.mae@gmail.com
  m.theoryx2@gmail.com
  m_sharer2002@yahoo.com
  maddiquam@gmail.com
  madebytobs@gmail.com
  madtownillustration@gmail.com
  madwomanjewelry@gmail.com
  maggieannecarter247@gmail.com
  mago.glassworks@gmail.com
  mai.lor651@gmail.com
  majestikk17@gmail.com
  makasa27@hotmail.com
  malikbphotography@gmail.com
  mandelmertz@gmail.com
  manidoo.aki@gmail.com
  mapsandscraps@gmail.com
  marcialvar430@gmail.com
  marialinsdayartist@gmail.com
  marieflong527@yahoo.com
  marjorierosemoore@gmail.com
  markestlund@gmail.com
  markloneart@gmail.com
  markmcleodnyc@gmail.com
  markreif@gmail.com
  marniehart1@comcast.net
  martinwren5@gmail.com
  martyharris@earthlink.net
  mary@yogamary.com
  marybird@uglydaisy.com
  maryn_72@msn.com
  marystowellart@gmail.com
  masonjgreen@gmail.com
  matt_lampi@yahoo.com
  mattfitzke@gmail.com
  matthew@multithought.com
  matthintzart@gmail.com
  mattsonivy@gmail.com
  mattzinstattoo@gmail.com
  maya@botanicalatelier.com
  mcca0862@umn.edu
  mccaylathoe@gmail.com
  mcguin1414@gmail.com
  mchiepeter@gmail.com
  mcjohnson034@gmail.com
  mcleggillustrations@gmail.com
  medievaljakes@gmail.com
  meena.a.subramanian@gmail.com
  megaleidoscope@gmail.com
  megan.tate13@gmail.com
  megan@happiehippiemn.com
  megan@meganbell.net
  mehuart@gmail.com
  melaniegrace78@hotmail.com
  merandaturbak@gmail.com
  merickson4720@gmail.com
  merk7373@yahoo.com
  messingwithmetal@gmail.com
  metal.mulisha.ag@gmail.com
  mettaren333@gmail.com
  mevrouwrozestudios@gmail.com
  mfleecas@gmail.com
  mgeislinger31@gmail.com
  mhill001@icloud.com
  mholbeck@kelliher.k12.mn.us
  mhphinstall@gmail.com
  miadevery@yahoo.com
  miasastroart@gmail.com
  michael.cervantes@comcast.net
  michael.h.wade@gmail.com
  michael@michaelgreenphoto.com
  michaelvartwork@gmail.com
  michayla.grbich.art@gmail.com
  michelle.holbeck@yahoo.com
  michelle.levy@kittyrevolution.org
  mikeycimino@gmail.com
  mikojohnson47@yahoo.com
  mindyhuntress@gmail.com
  mindyjohnson31@gmail.com
  miquela.wagner@gmail.com
  missastrospooked@gmail.com
  missmixalots@gmail.com
  misterviddy@gmail.com
  mitchhattenart@gmail.com
  mitchwichser@gmail.com
  mixiemgmt@gmail.com
  mjd.milam@gmail.com
  mjmasilko@yahoo.com
  mlauramiller@aol.com
  mllaster07@gmail.com
  mo.olaughlin.art@gmail.com
  mobrien2010@gmail.com
  mohamed_hersi@live.com
  mollierae35@gmail.com
  molly.borakove@gmail.com
  molly.m.sharpe@gmail.com
  mollyharingart@gmail.com
  mollyolimb@gmail.com
  moremilkmpls@gmail.com
  mouseworkglass@yahoo.com
  moy718@gmail.com
  mpeg432@gmail.com
  mplshousemusic@gmail.com
  mrbloosman@gmail.com
  mrjoeh95@gmail.com
  mrskatepearce@yahoo.com
  mrtattoo10@gmail.com
  ms.dporter@icloud.com
  msmelissakay@live.com
  msndvk@yahoo.com
  msraella@yahoo.com
  mtheorye@gmail.com
  mttfsv@gmail.com
  multimediamala@yahoo.com
  murdocevades@gmail.com
  murp0864@live.com
  mweyh2@gmail.com
  mwilson1986@live.com
  mxacp96@gmail.com
  mya1simpson@gmail.com
  myamakesstuff@gmail.com
  mychalbatson@gmail.com
  mysticchef@yahoo.com
  n.e.thompsonmusics@gmail.com
  narcfighter@gmail.com
  nathanolivarez.art@gmail.com
  nathanrenkenart@yahoo.com
  nathanwmlewis@gmail.com
  nathonovitch@yahoo.com
  nbestul@yahoo.com
  nealemaendler@gmail.com
  nehemiahmathews77@gmail.com
  nemonoai@gmail.com
  nessamelon@gmail.com
  nettatrends44@yahoo.com
  neyag1309@gmail.com
  nicholasjhermoza@gmail.com
  nickchrisols@gmail.com
  nicknaqart@gmail.com
  nicolebrittanykiel@gmail.com
  nicolen143@icloud.com
  nightb.tch00@gmail.com
  nikobruh@gmail.com
  nina.t.jepson@gmail.com
  ninarivera.art@gmail.com
  njfuelberth@gmail.com
  nmaliscke@gmail.com
  nmthul@gmail.com
  nnygonzalez@gmail.com
  noah.heath66@gmail.com
  noblesoapgallery@gmail.com
  nomadictwirler@gmail.com
  northwomandesign@gmail.com
  nostalgiadahling@outlook.com
  nvoltage@comcast.net
  nycole21@gmail.com
  obrien.railroad@gmail.com
  odamyou@gmail.com
  oldtownflat@yahoo.com
  oliviadecaigny@gmail.com
  oliviaridlon@gmail.com
  orishnnani@yahoo.com
  orisoncrafts@gmail.com
  osmofolia@gmail.com
  pacewinkels@gmail.com
  paintingsbybrandon@gmail.com
  pandorasframe@gmail.com
  panjenambao@gmail.com
  paraparapapanda@gmail.com
  paul0623@umn.edu
  paulrcushman@gmail.com
  pdevriesart@hotmail.com
  peaceomind101@gmail.com
  perkostrangerthings@gmail.com
  peter@eight-21.com
  peter@midcentury-music.com
  petewmp@gmail.com
  phankee81@gmail.com
  phillmenge3@gmail.com
  phoenixroberts@comcast.net
  pipergibson13@gmail.com
  planetaryqueer@gmail.com
  plataniafinearts@gmail.com
  plrude@outlook.com
  pmnone@yahoo.com
  poffc13@outlook.com
  pollardartwork@gmail.com
  poured.planets@gmail.com
  powell44amg@gmail.com
  prestonh758@gmail.com
  priyaa.tuttle@gmail.com
  pruitt.monique1994@gmail.com
  pseudomanitou@gmail.com
  psilocybin651@yahoo.com
  qtgigglis@aol.com
  rabashian@hotmail.com
  rachaelkhunter2@gmail.com
  rachel.a.allison@gmail.com
  rachspringman@gmail.com
  raffertydesign@gmail.com
  ragadoomatroska@gmail.com
  rajinethequeen@gmail.com
  ranebochild@gmail.com
  raniellej.art@gmail.com
  ravengleason666@gmail.com
  rayreartifacts@gmail.com
  rebecca.natt@gmail.com
  refindworks@gmail.com
  reillyjulius@gmail.com
  reimana17@yahoo.com
  renaecole24@gmail.com
  renee.boynton.art@gmail.com
  resterlop@gmail.com
  reuben.anderson01@gmail.com
  rhowlett7116@yahoo.com
  richard.v.houff@gmail.com
  richards.gwen@gmail.com
  rileyharrison@gmail.com
  rjoy.braun@gmail.com
  rjtx85@gmail.com
  roadkillkaily@gmail.com
  rock.johnsen@gmail.com
  ronbrown612@yahoo.com
  room2grow@gmail.com
  rose.oner98@gmail.com
  roseberry.lauren@yahoo.com
  rosehipps333@gmail.com
  rosesimaginarium@gmail.com
  rossowjairid@gmail.com
  rowlesglass@outlook.com
  rpalbicki@gmail.com
  rpowers@miquashi.com
  ru73@yahoo.com
  rubenpagitt92@gmail.com
  russjames62@gmail.com
  ryanhuggettphotography@gmail.com
  ryanlavern@gmail.com
  s-huangs@hotmail.com
  sabatanna31@gmail.com
  sadee.thompson@gmail.com
  sagmoeb@gmail.com
  saintbysuki@gmail.com
  salenaevans0@gmail.com
  salsaeed92@gmail.com
  samie11@mail.com
  sammorrow147@gmail.com
  sammystar81@yahoo.com
  samueljacob.wilbur@gmail.com
  samuelstaudt@hotmail.com
  sanderk6@gmail.com
  sarahhickmanart@gmail.com
  sarahlars2016@gmail.com
  sarahmsosa@gmail.com
  sassynailzpressons@gmail.com
  savvyydesignsco@gmail.com
  scarmichael432@gmail.com
  schuesslerj73@gmail.com
  schwm01@yahoo.com
  scribbledbypeach@gmail.com
  sdrentlaw@gmail.com
  selmonj@ymail.com
  sensiblechaos.nease@gmail.com
  serenaa.black@gmail.com
  serpentenial@gmail.com
  seth.stratton7@gmail.com
  sethblewett25@gmail.com
  sethriess0@gmail.com
  sgsteller@gmail.com
  shakuntaladesign@yahoo.com
  shane@shaneandersonillustrations.com
  shanepdavis89@gmail.com
  shannon.durphy@gmail.com
  shannon.twohy@gmail.com
  shaunegary@gmail.com
  sheepathequeen@gmail.com
  shelby.a.cate@gmail.com
  shelbyelarson.etsy@gmail.com
  shelitaartworld@gmail.com
  shellkelleyart@gmail.com
  shellucinationsart@gmail.com
  shelmil2001@icloud.com
  shepa057@gmail.com
  shexclusive@gmail.com
  shockley.christopher@gmail.com
  shuazongav@gmail.com
  silinsmason@gmail.com
  skanderson310@gmail.com
  skip.wilson@hotmail.com
  skullwolfjack@gmail.com
  sleopoldsullivan@gmail.com
  smplypouredout@gmail.com
  smwilson014@gmail.com
  sooltanmadsen@gmail.com
  sophiedanielson@mac.com
  soulfirebygypsimoon@gmail.com
  spacecase.cafe@gmail.com
  spencerflojoart@gmail.com
  spencersilver@mac.com
  spilkerbrandcheesecake@gmail.com
  spiraliaworld@gmail.com
  splashofroyaltydesignz@outlook.com
  spoonandtheory@gmail.com
  srgunn02@gmail.com
  srwomeldorff@gmail.com
  st8ofinfinity@gmail.com
  stannardly@gmail.com
  stargazerbyc3@gmail.com
  starseedurban@gmail.com
  startaflame7@gmail.com
  stef84@icloud.com
  stemig2010@gmail.com
  steve.schroeder.art@gmail.com
  stevekellerart@gmail.com
  steven.guilford.612@gmail.com
  stitchedbynicd@gmail.com
  storm.m612@gmail.com
  stpaulcameraguy@gmail.com
  studi0takecare@gmail.com
  suejo555@gmail.com
  sunlitartdesign@gmail.com
  sunshinecollectivebylola@gmail.com
  susan@susanopitz.com
  suzenbeach@gmail.com
  suzenjuel@gmail.com
  suzy.jones25@gmail.com
  syoungillustration@gmail.com
  talismanfinds@gmail.com
  talissamehringer@gmail.com
  tanner.bosak@yahoo.com
  tanyawhite784@gmail.com
  tattooinkpop@gmail.com
  taylorreichel@live.com
  tcpartybus@gmail.com
  teahjoy14@gmail.com
  tessamquale@gmail.com
  tessi.m.russell@gmail.com
  teygaen@gmail.com
  theartoftovelee@outlook.com
  thebestmovempls@gmail.com
  thedan@sleepydans.com
  thelastyavi@gmail.com
  thenortherngroove@yahoo.com
  theoreticallyokay@gmail.com
  thesolidaritymovement@gmail.com
  thomasbartlettjewelrydesigns@gmail.com
  thomasre3@gmail.com
  threeandonesol@gmail.com
  timeintopixels@hotmail.com
  timmahlpacello@gmail.com
  tira.erdman@gmail.com
  tlangevin24@gmail.com
  tlundmark88@gmail.com
  tmcowien@hotmail.com
  tmcowien@mcad.edu
  tmillsfilms@gmail.com
  tmontez523@gmail.com
  tobersonstudios@gmail.com
  tomarolaney@yahoo.com
  tonicthoughtstudios@gmail.com
  tony.jacobson11@gmail.com
  topphotos1@hotmail.com
  torch1313@gmail.com
  totallyrighteousconcepts@gmail.com
  touristprisonphotography@gmail.com
  tracie@traciethompson.com
  tracybrewsterhagg@gmail.com
  travisabaddon@gmail.com
  triballovedesigns@gmail.com
  trinity0107@hotmail.com
  tripleaquarian@yahoo.com
  trysttriggerartworks@gmail.com
  tscrewdriver@yahoo.com
  tsunami670@hotmail.com
  ttorreson@yahoo.com
  tugbaozt096@gmail.com
  tulips55963@gmail.com
  turnthepaigeart@gmail.com
  twila.singh@gmail.com
  ty8boom@gmail.com
  tylriii999@gmail.com
  tythomas1786@gmail.com
  uglyfruits.artistry@gmail.com
  underground.deziner@gmail.com
  unimaginativeart@gmail.com
  unohuu@me.com
  urbanomoises1@gmail.com
  urdesignangel@gmail.com
  vernasgarrison@gmail.com
  victoriat.sharp@gmail.com
  vincenzio.donatelle@gmail.com
  vintagedollhouse@gmail.com
  violet.lux.official@gmail.com
  virginiaspurrier@gmail.com
  vividvioletaura@gmail.com
  walia.hasan@gmail.com
  walkoffa8th@gmail.com
  wally.mahnke@gmail.com
  walter@horishnyk.com
  wapart9@hotmail.com
  wbcwaterboxco@aol.com
  wejet420@gmail.com
  whispurrwoods@gmail.com
  will.raymond834@gmail.com
  william.hessian@gmail.com
  williamjhelm86@gmail.com
  willverdeja@yahoo.com
  wilsonkelly227@gmail.com
  wingsonjordan@yahoo.com
  winona.vetsch@gmail.com
  winonavoldart@gmail.com
  woaaa999@gmail.com
  woolysworld423@gmail.com
  wormylines@gmail.com
  xiongx38x@gmail.com
  xpittmanart@gmail.com
  xxlivdragonxx@gmail.com
  youngnfilthyco@gmail.com
  zakiahgoff@gmail.com
  zandrieneh@gmail.com
  zanettad@hotmail.com
  zdimeroz@gmail.com
  zealouspaintings@live.com
  zebshaffer@gmail.com
  zencatstudios@gmail.com
  zrowe94@gmail.com
  zvwalby@gmail.com
]

applicants = [
  { email: "ajan0033@hotmail.com",              status: "approved", from_invite: true  },
  { email: "energyjunctions@gmail.com",          status: "approved", from_invite: true  },
  { email: "getme2.mg@gmail.com",                status: "approved", from_invite: true  },
  { email: "krazykara.herring1@gmail.com",       status: "approved", from_invite: true  },
  { email: "nathanolivarez.art@gmail.com",       status: "approved", from_invite: true  },
  { email: "rileyharrison@gmail.com",            status: "approved", from_invite: true  },
  { email: "sunshinecollectivebylola@gmail.com", status: "approved", from_invite: true  },
  { email: "kidkippo@gmail.com",                 status: "pending",  from_invite: true  },
  { email: "lilivsdraws@gmail.com",              status: "pending",  from_invite: true  },
  { email: "miasastroart@gmail.com",             status: "pending",  from_invite: true  },
  { email: "storm.m612@gmail.com",               status: "pending",  from_invite: true  },
  { email: "tulips55963@gmail.com",              status: "pending",  from_invite: true  },
  { email: "courtneygreer@heyvoxxy.com",         status: "pending",  from_invite: false },
  { email: "justin@pancakesandbooze.com",        status: "pending",  from_invite: false }
]

invitations = {}
inv_ok = 0
inv_fail = 0

invited_emails.each do |email|
  begin
    contact = VendorContact.create!(
      organization: org,
      name:         email.split("@").first,
      email:        email,
      status:       "new",
      contact_type: "lead"
    )
    inv = EventInvitation.create!(
      event:          event,
      vendor_contact: contact,
      status:         "sent"
    )
    invitations[email] = inv
    inv_ok += 1
  rescue => e
    puts "FAIL invite #{email}: #{e.message}"
    inv_fail += 1
  end
end

puts "Invitations: #{inv_ok} created, #{inv_fail} failed"

reg_ok = 0
reg_fail = 0

applicants.each do |row|
  begin
    inv = row[:from_invite] ? invitations[row[:email]] : nil
    r = Registration.new(
      event:              event,
      vendor_application: artists_app,
      event_invitation:   inv,
      email:              row[:email],
      name:               row[:email].split("@").first,
      business_name:      row[:email].split("@").first,
      vendor_category:    "Artists",
      status:             row[:status],
      payment_status:     "pending"
    )
    if r.save
      puts "OK [#{row[:status]}] #{row[:email]}"
      reg_ok += 1
    else
      puts "FAIL #{row[:email]}: #{r.errors.full_messages}"
      reg_fail += 1
    end
  rescue => e
    puts "FAIL #{row[:email]}: #{e.message}"
    reg_fail += 1
  end
end

puts "Registrations: #{reg_ok} created, #{reg_fail} failed"

Registration.set_callback(:create, :after, :send_confirmation_email)
Registration.set_callback(:update, :after, :send_status_update_email)

puts ""
puts "EventInvitations: #{event.event_invitations.count}  (expected 1040)"
puts "Registrations:    #{event.registrations.count}  (expected 14)"
puts "  approved:       #{event.registrations.where(status: 'approved').count}  (expected 7)"
puts "  pending:        #{event.registrations.where(status: 'pending').count}  (expected 7)"
