org   = Organization.find(4)
event = Event.find_by(slug: "san-francisco-pancakes-booze-art-show")
raise "Event not found!" if event.nil?
raise "Event is not live!" unless event.is_live
artists_app = event.vendor_applications.find_by(name: "Artists")
raise "Artists VendorApplication not found!" if artists_app.nil?

puts "Org: #{org.id} — #{org.name}"
puts "Event: #{event.id} — #{event.title} (live: #{event.is_live})"
puts "Artists app: #{artists_app.id}"

Registration.skip_callback(:create, :after, :send_confirmation_email)
Registration.skip_callback(:update, :after, :send_status_update_email)
puts "Email callbacks disabled."

invited_emails = %w[
  00seth@gmail.com
  26eacosta@gmail.com
  333ficklin@gmail.com
  4lexc4m@gmail.com
  6savage6butcher6@gmail.com
  8zenmind8@gmail.com
  9amart.etsy@gmail.com
  a.worm.friend@gmail.com
  aaaufromthebay@gmail.com
  aaillustration@gmail.com
  aanhalt@gmail.com
  aaorosco805@aol.com
  abalonegreg@gmail.com
  abbie.bellpeper@gmail.com
  abefagorala@gmail.com
  abidebymitherz@yahoo.com
  abigail.lee.goldberger@gmail.com
  abstractaffirms@gmail.com
  abstractsociety.us@gmail.com
  ac.jc.arts@gmail.com
  achaiadippel@live.com
  acrylicchick@gmail.com
  adamguzzo@gmail.com
  adamsbrendan85@gmail.com
  adilahsan9@gmail.com
  aditimaluart@gmail.com
  admin-pix@pixxstar.art
  admin@solariumartstudio.com
  adventureofaunicorn@gmail.com
  afrancoarts@gmail.com
  agrcreations@hotmail.com
  aharrison2088@gmail.com
  ahjahenryart@gmail.com
  ahn.benjamin@yahoo.com
  aidairving@gmail.com
  ainswo@yahoo.com
  aivanhoe@gmail.com
  ajabwiley@gmail.com
  ajacks_5100@yahoo.com
  ajandrade@outlook.com
  ajoseph3993@gmail.com
  akaa.draw@gmail.com
  akarx4@gmail.com
  akbaker_7@hotmail.com
  akeemraheem8@gmail.com
  akshaya.natarajan495@gmail.com
  akshayanatarajan495@gmail.com
  al3xfelicity@gmail.com
  alaart@gmail.com
  alan.m.grumet@hotmail.com
  alana.oh.my@gmail.com
  alanachlarson@gmail.com
  alandwheeler@gmail.com
  alaricbarca@gmail.com
  alatorreartsanddesigns@gmail.com
  alberto@albertoybarra.com
  albin.tobias.lund@gmail.com
  albright.bryce@gmail.com
  alcalalesley@gmail.com
  alegermann@gmail.com
  alejandrohaas@yahoo.com
  alenyajsart@gmail.com
  alex@tucupi.biz
  alexadunham@gmail.com
  alexandersuelto@gmail.com
  alexmhoulton@gmail.com
  alicehophotography@gmail.com
  alicepau7@gmail.com
  alinasage93@gmail.com
  alinob.artus@gmail.com
  alisalego24@gmail.com
  alisamj123@gmail.com
  alisasokolov42@gmail.com
  alisha.coelho92@gmail.com
  alisonsileo@gmail.com
  alissa_cook@yahoo.com
  allegraj89@gmail.com
  allie.barham@gmail.com
  almanzanojr@gmail.com
  alva.svoboda@gmail.com
  alycia__walter@outlook.com
  alykasa@gmail.com
  amadoadilly@gmail.com
  amandagracesanchez@gmail.com
  amandaloyer@yahoo.com
  amandart@gmail.com
  amauraarts@gmail.com
  amayah12371@gmail.com
  ambearts@gmail.com
  amberdanthomas@yahoo.com
  ambrosedial@proton.me
  amersonfineart@gmail.com
  amightyleanos@icloud.com
  amilovelace@gmail.com
  amir@lot78studio.com
  amorales350@hotmail.com
  amorgan415@gmail.com
  amramirez555@gmail.com
  amuddle@aggartstudio.com
  amy@salvadorkitti.com
  amyemeraldprindle@gmail.com
  amylcopperman@gmail.com
  analuis4lfaro@gmail.com
  analyn40887@gmail.com
  andersonarts1@gmail.com
  andie_vallee@yahoo.com
  andrea@moonbugwings.com
  andreanunezdecaceres@gmail.com
  andreea@bvdboutique.com
  andremiloslavich@gmail.com
  andresotount@gmail.com
  anetrastudioinfo@gmail.com
  angelaelacioefe@gmail.com
  angeldeltafrog@gmail.com
  angelgarcia4602@gmail.com
  angelisartstudio@gmail.com
  angelllopez81@gmail.com
  angelmatthewsart@gmail.com
  angeltnlin@gmail.com
  angrygeniusiv@gmail.com
  aniyahkeith14@gmail.com
  anjali.vemuri@gmail.com
  ann@anngrini.com
  anna@asv-studios.com
  annamika2020@gmail.com
  annampdx@yahoo.com
  anne@annepauley.com
  annelisefmckay@gmail.com
  annepennypacker@gmail.com
  annoyingmouse@mail.com
  anthonygillen621@gmail.com
  anthonymace650@gmail.com
  antkhall@gmail.com
  antoniamiller354@gmail.com
  antoniopreza415@yahoo.com
  antonioroliz777@gmail.com
  anvillagran1@gmail.com
  anyark@gmail.com
  aok.artist@gmail.com
  apmsound@yahoo.com
  aprillaks52@gmail.com
  aquafreesoul@gmail.com
  archana.gurrewala96@gmail.com
  argeeg@gmail.com
  arianabethell13@gmail.com
  arieleikolyons@gmail.com
  arielleecrenshaw@gmail.com
  ariesartsf@gmail.com
  ariesiamproduction@gmail.com
  ariyaharrison523@gmail.com
  armando.delgado.arroyo@gmail.com
  arogers247@gmail.com
  art.by.xtina@gmail.com
  art.class.with.anna@gmail.com
  art.theajstudio@gmail.com
  art@deepthawtz.com
  art@rifflestudio.com
  artaaaheart@gmail.com
  artbuydexter@gmail.com
  artby_joaquin@yahoo.com
  artbyadrianam@gmail.com
  artbyakshaya@gmail.com
  artbyamarilis@gmail.com
  artbycharlenemarie@gmail.com
  artbyjdotson@yahoo.com
  artbykomel@gmail.com
  artbykootsoo@gmail.com
  artbylaurus@gmail.com
  artbypree@gmail.com
  artbyrobbie24@gmail.com
  artbywestcoastsuma@gmail.com
  artbywillscott@gmail.com
  artfunkpaintings@gmail.com
  arthopeguinn@gmail.com
  arthurodesskiy@gmail.com
  artist_one@me.com
  artistchris@gmail.com
  artisticallyatheart@gmail.com
  artisticdreamist@gmail.com
  artmoneygallery@gmail.com
  artofericayoshino@gmail.com
  artsfury@gmail.com
  arttwerkmary@gmail.com
  ary.ruano@gmail.com
  as3.yang@gmail.com
  asaulgoldman@gmail.com
  ashas.martin@gmail.com
  ashaulis@lucasfilm.com
  ashelton3@gmail.com
  ashely@1320studios.com
  ashleigh.addict.art@gmail.com
  ashley.grice16@gmail.com
  ashleycousin@gmail.com
  ashleykseo@gmail.com
  ashlie@akego.art
  asiashame@icloud.com
  astonishinghooligans@gmail.com
  asukajewelry@gmail.com
  asukausa125@gmail.com
  atchison.katy@gmail.com
  audracadabra@gmail.com
  audreyanna_101@outlook.com
  audreydurazzo67@gmail.com
  audreymarilynjacobs@gmail.com
  audreysalindong17@gmail.com
  augustewfallon@gmail.com
  autistic.moodi.artist@gmail.com
  auto@dustymindscollective.com
  autumnadeyan0@gmail.com
  autumnbreearts@gmail.com
  avarice@gmail.com
  avashannon24@gmail.com
  avien.void@gmail.com
  aweetumns.art@gmail.com
  awestone98@gmail.com
  awyopp@hotmail.com
  axl235@yahoo.com
  aydenoliver@me.com
  ayesalove111@gmail.com
  ayla.mgmt@gmail.com
  azanonanthony@gmail.com
  b.warren.box@gmail.com
  bableenchopra20@gmail.com
  babylopezapparel@gmail.com
  barelyawakekalee@gmail.com
  bariyacchi@gmail.com
  bassarch100@gmail.com
  bayareasharpie@icloud.com
  bballbrian234@gmail.com
  bdubfield@gmail.com
  beadornedbyreni@gmail.com
  beatfreaks88@gmail.com
  beaztog40@gmail.com
  belardi.shannon@gmail.com
  bell@bellquintao.com
  bellahuang.hyh@gmail.com
  bemodi87@yahoo.com
  benhaas95@gmail.com
  benhumphrey3@gmail.com
  benjamin.butler33@gmail.com
  benjamin@cheersboydart.com
  benjammin264@gmail.com
  berardi@live.com
  bermudezlemus13@hotmail.com
  bernadettebohandesign@gmail.com
  bernadinepreetha@icloud.com
  bernielumba11@gmail.com
  besoefilmz@gmail.com
  biankalove@ymail.com
  bibibenitez94@gmail.com
  big10production@gmail.com
  biijonart@gmail.com
  billseet@gmail.com
  billy.chiechi@gmail.com
  birenamart@gmail.com
  bistrong.create@gmail.com
  bjengcomix@gmail.com
  blacklightrobot@live.com
  blackrayven@me.com
  blairbradshaw@gmail.com
  blakefoster1@gmail.com
  blankdsk@gmail.com
  blazen7custom@yahoo.com
  bleyyyk@gmail.com
  blkbabedesigns@gmail.com
  blurthelines2@hotmail.com
  blvbelieveinyourdream@gmail.com
  bmariem89@me.com
  bmccall25@yahoo.com
  bmiller@chefsinamerica.org
  bnavarre94@yahoo.com
  bobbycoleman2@gmail.com
  bombooksurge@gmail.com
  bonniepolsonphotography@gmail.com
  booking@izinfinite.net
  bountifuldejavu@gmail.com
  bowlesmackenzie@gmail.com
  boywithbrushes@gmail.com
  bozzinimark@gmail.com
  bozzychains@gmail.com
  branca.n@gmail.com
  brand_o67@yahoo.com
  brandondicks@gmail.com
  brandonhurley4@gmail.com
  brandonjosephbaker@yahoo.com
  brandonmeinsphotography@gmail.com
  brandonriza@gmail.com
  brecord628@gmail.com
  brenoaragon@hotmail.com
  brerdartist@gmail.com
  brianne.w.923@gmail.com
  brianwatsongolf@gmail.com
  briespiel@gmail.com
  briss.gonzales@gmail.com
  brittanyarieloddieo@gmail.com
  brittsters58_20@yahoo.com
  brobinson1094@gmail.com
  brockhuguley@gmail.com
  brokeandabsurd@gmail.com
  brookebuchanan@berkeley.edu
  brookeytp@gmail.com
  brownr24@gmail.com
  bryahnap@hotmail.com
  burningcora@gmail.com
  businessatk28@gmail.com
  bvalenzueladesigns@gmail.com
  bykevincombs@gmail.com
  bymathai@gmail.com
  cabrales.art@gmail.com
  cadenayrosas@gmail.com
  caityfares@yahoo.com
  calibird77@gmail.com
  californiaironkid@gmail.com
  calvinlaiart@gmail.com
  cam.larsonarts@gmail.com
  cameron@cegart.com
  camilamcostoya@gmail.com
  campos_design@yahoo.com
  camrynmichelle@gmail.com
  canehowlet@gmail.com
  cannabrer@gmail.com
  captainjesseblack@gmail.com
  caragoldstein1@gmail.com
  carlosfdlr@yahoo.com
  caroline.k.song@gmail.com
  carolinekirincic@yahoo.com
  carsonjamesphoto@gmail.com
  casey.castille@gmail.com
  caseyjhaugen@gmail.com
  caseyknightart@gmail.com
  cashonlyphotography@gmail.com
  cassandra.sechler@gmail.com
  castellanosmark86@yahoo.com
  catdesign99@gmail.com
  catherine.e.olson@gmail.com
  catherinethomas466@gmail.com
  catrina0330@gmail.com
  cawing88@gmail.com
  cbdbyoce@gmail.com
  cbeuhler@gmail.com
  cbfox1973@gmail.com
  cdlee3@gmail.com
  cdurden.ca@gmail.com
  ceciliacecelau16@gmail.com
  cedar.m.francis@gmail.com
  ceezrcq@gmail.com
  celise@artbycelise.com
  ceribra14@gmail.com
  cezhang642@gmail.com
  chai.creations.clay@gmail.com
  chancecarstensen@me.com
  chanelchavira93@gmail.com
  channel13co@gmail.com
  chaosbalanceart@gmail.com
  charliepeople427@gmail.com
  chasindoodles@gmail.com
  chatalberto1@gmail.com
  chaverriartistic@gmail.com
  cheholts@gmail.com
  chelsea.c.falcone@gmail.com
  chelseabrie@gmail.com
  chelseamandell@yahoo.com
  chen.riki@gmail.com
  cherrylopezart@gmail.com
  cheyanne.pm@gmail.com
  cheyeisert@gmail.com
  chicxdegallo@gmail.com
  chimoska@yahoo.com
  chistylezs@gmail.com
  chitvan.atpug@gmail.com
  chloe.peak@gmail.com
  chloeqms@gmail.com
  chocolatecity.art@gmail.com
  choosemoneylifestylebrand@gmail.com
  chris@outboundlinesart.com
  chrispark99@gmail.com
  christine.at@outlook.com
  christinedorfer@icloud.com
  christiny@berkeley.edu
  christophernolasco23@yahoo.com
  christopherpblay@gmail.com
  chuck@whelon.com
  chuibarart@gmail.com
  cibra100@gmail.com
  cicadascrafts@gmail.com
  cindy.ashley.ramirez@gmail.com
  citrinelunar@gmail.com
  cjheru@yahoo.com
  cking@cca.edu
  ckrausart@gmail.com
  claire.s.crowley@gmail.com
  clairetweedy@gmail.com
  clarejoelson9193@gmail.com
  clarissa.marchia@gmail.com
  cloudzcraftz@gmail.com
  cmcpablo@gmail.com
  cmcphotocraft@gmail.com
  cmichalik9378@gmail.com
  cmlsbusiness@gmail.com
  cmoon@usa.com
  colleenpovey@gmail.com
  collins773.bc@gmail.com
  colorfullyweird0@gmail.com
  colorsofclara@gmail.com
  comicauthor.jr@gmail.com
  conartistfitness@gmail.com
  congabat@gmail.com
  connect@autumnwindjames.com
  consciouscare101@gmail.com
  contact.amymariela@gmail.com
  contact@artfromrosalie.com
  contact@astridhernandez.com
  contact@neverrelaxed.com
  contact@roberthasson.art
  contact@siennafaye.com
  cooperxeno@gmail.com
  corbindeshazo777@gmail.com
  cordiedan@gmail.com
  corettalnewson@gmail.com
  corina@corinafoto.com
  corina@soulcraftapotheca.com
  corybowman90@yahoo.com
  cosmicghostprincess@gmail.com
  cosmohlina@gmail.com
  cottonturner@gmail.com
  courage_smith@yahoo.com
  courtney@peopleartmusic.com
  courtneygreer@heyvoxxy.com
  couturehah@gmail.com
  cpikerward@gmail.com
  crashart1@gmail.com
  cray1984@outlook.com
  create-art@outlook.com
  creativekerr@gmail.com
  crikbrand@gmail.com
  crisisartist@gmail.com
  cristianrpolanco@gmail.com
  crosse.alyssa@gmail.com
  cruanoart@gmail.com
  crystacular@gmail.com
  crystalvisionsjewelry@gmail.com
  cstorozkova@gmail.com
  cterzes@hotmail.com
  cubaisakatpatina@gmail.com
  cullinane55@yahoo.com
  cunningham.bonnie@gmail.com
  cunninghamolivia@gmail.com
  cuong671@gmail.com
  cupofnyx@gmail.com
  cynta.cam@gmail.com
  cynthiadouaiher@gmail.com
  d.digglesworth@gmail.com
  d.h1923camino@gmail.com
  d.rellejingco@gmail.com
  d1healingstone@gmail.com
  dadadoodlesart@gmail.com
  dagrisales@gmail.com
  dahlinglili@gmail.com
  daize1984@pacbell.net
  dakurtz@dakurtz.com
  dallasgoins19@gmail.com
  danaelenda@gmail.com
  dananew@udel.edu
  dandborodin@gmail.com
  dangthatlily@hotmail.com
  danhudsonartist@gmail.com
  daniel9965@gmail.com
  daniele.erville@gmail.com
  danielgilbreathfineart@yahoo.com
  danielle.bellantonio@gmail.com
  danimack3@gmail.com
  dannerbridget@gmail.com
  danny.moscoso@gmail.com
  dannystlartist@gmail.com
  danvee80@gmail.com
  danya.dye@gmail.com
  danyelchurch@gmail.com
  daphnelhays@gmail.com
  darellerichard@rishart1of1.com
  darinpaints@gmail.com
  david@foundsumart.com
  david@shineon.studio
  davidcastaneda92@gmail.com
  davidraythurmon@yahoo.com
  davidrdraws@gmail.com
  daynajaret@gmail.com
  daysumler@gmail.com
  dazedbeast1@gmail.com
  dboonedock@gmail.com
  dbrigitte.a@gmail.com
  dbvc365@gmail.com
  dcolbeck79@gmail.com
  dearathouston@gmail.com
  deborahtanaka@ymail.com
  debradarlingface@gmail.com
  dedeauxart@gmail.com
  dedosrocks@gmail.com
  deechenceramics@gmail.com
  deedubco@gmail.com
  deja.jovon@gmail.com
  delaneyh0813@gmail.com
  delvoyegeniverm@gmail.com
  demetritylerphotography@gmail.com
  dennislaray@gmail.com
  designbgeorge@gmail.com
  destiniethomas01@gmail.com
  devin.brice1@gmail.com
  dexlongboardco@gmail.com
  dfainelli@gmail.com
  diana.hartman@gmail.com
  diegoe2017@gmail.com
  diegolmejia@yahoo.com
  differentartworks@gmail.com
  digibotttttt@gmail.com
  dilciagiron@gmail.com
  dizwaltney@hotmail.com
  djeromebragg@gmail.com
  djmcdermott2017@gmail.com
  djshadowspirit@gmail.com
  dmnloyola@yahoo.com
  dnakah@comcast.net
  dog.nougat@gmail.com
  dohertycarr@gmail.com
  domtdesigns@gmail.com
  donavondb@msn.com
  dongze1985@gmail.com
  donkeybaster@gmail.com
  donnalim_fitness@yahoo.com
  doodlybish@gmail.com
  dorientaylorart@gmail.com
  dorovalley@gmail.com
  doubledownzine@gmail.com
  dounyartist@gmail.com
  dpaniagua524@gmail.com
  dplawlorfilms@gmail.com
  dreaartist@gmail.com
  dreamdrifterdesigns@gmail.com
  drew.roulette@gmail.com
  drewbhall3@gmail.com
  drod36@gmail.com
  drpaluga@gmail.com
  druidichabit@gmail.com
  drummergrl4ever@yahoo.com
  dstinyp@outlook.com
  dunlap.calee@gmail.com
  dustywingsillustration@gmail.com
  duvox1979@gmail.com
  dwashington0075@gmail.com
  dylanpalmerart@gmail.com
  e.interlicchia@gmail.com
  e.s.peik@gmail.com
  ealm728@gmail.com
  eastbayjilly@gmail.com
  ebndaly@gmail.com
  echalk0507@gmail.com
  ed.aparicio4@gmail.com
  ed.reed@hotmail.com
  eddamdavila@gmail.com
  edietrautwein@gmail.com
  edsart44@gmail.com
  eelcostello@gmail.com
  ehawkinson32197@gmail.com
  ehewlettvisuals@gmail.com
  eliahtumalan@gmail.com
  elicather626@gmail.com
  elijahwanco18@gmail.com
  elisagonsalves@yahoo.com
  eliteminds1of1@gmail.com
  eliwilliams1337@gmail.com
  elizabethserafino@gmail.com
  elizabethshayart@gmail.com
  ellamartyn@gmail.com
  ellamyerslipton@gmail.com
  ellendeeh@gmail.com
  ellyzen@gmail.com
  elser42@yahoo.com
  eltxutxo19@yahoo.com
  eluterio.lopez@gmail.com
  elvinbdeguzman@gmail.com
  elworthystudio@gmail.com
  elyhorses@gmail.com
  emailitcaro@gmail.com
  emailryane@gmail.com
  emaupome@gmail.com
  emerald.outlaws@gmail.com
  emilie.boras@gmail.com
  emilybee3@gmail.com
  emilychenceramics@gmail.com
  emilyfujiemair@gmail.com
  emilygenevieve@gmail.com
  emilypascal@gmail.com
  emilywenner@hotmail.com
  emmaaguilar23@yahoo.com
  emmarosesperry@gmail.com
  emmy.gengler@softjourn.com
  emoweaselart@gmail.com
  emrad2000@gmail.com
  enigmo76@gmail.com
  enterthemelon@gmail.com
  eraciopp@gmail.com
  eric.d.blumenthal@gmail.com
  ericadyuen@gmail.com
  ericaearl07@gmail.com
  erick.lennin@gmail.com
  erick.palafox.phd@gmail.com
  ericshawnthompsonjr@gmail.com
  erifkind@gmail.com
  erika.underseahag@gmail.com
  erin.the.vance@gmail.com
  erinkatherinebatess@gmail.com
  erinroo@gmail.com
  eroinsart@gmail.com
  erousartesenias@yahoo.com
  erwhartelius@gmail.com
  esclowette5977@icloud.com
  eshaidelacruz@gmail.com
  espellegrini@me.com
  esthert1217@gmail.com
  eugeneanthonyrodriguez@gmail.com
  eurayo@gmail.com
  evanjonesmedia@gmail.com
  evecolmus@gmail.com
  evelynsart@gmail.com
  everestzak@gmail.com
  evieh325@gmail.com
  evies.sketches@gmail.com
  evilsebastian@yahoo.com
  evinsart@aol.com
  evolution_chamber@hotmail.com
  eyeinmysight@gmail.com
  eyezofthagardenzen@gmail.com
  fancybaybee@gmail.com
  farnazmd95@gmail.com
  fatainamore@gmail.com
  fborgatta@puppetfigures.com
  fefghinn@gmail.com
  ferrismartinez1986@gmail.com
  fgoarmy@gmail.com
  fiammydizon@gmail.com
  fitamaravilla5150@gmail.com
  five5ghosts@gmail.com
  flashesoforange@gmail.com
  flatroundplastic@gmail.com
  flor_breeze@yahoo.com
  fluidmotion.customs23@gmail.com
  flygradebeads@gmail.com
  fmiranda2899@yahoo.com
  fmwalker01@gmail.com
  fofutaart@hotmail.com
  fog.png@gmail.com
  followyourhipstars@hotmail.com
  fontenotakisha@gmail.com
  fonzerelli415@gmail.com
  fonziesartisanalgoods@gmail.com
  forresterdesign@hotmail.com
  fortandbay@gmail.com
  forumgala05@gmail.com
  foundsumart@gmail.com
  fpcread@gmail.com
  franciscotroy311@gmail.com
  frank.lindberg@yahoo.com
  frantomrussell@gmail.com
  freddiesgottadance@gmail.com
  freeflyeb@gmail.com
  freitasperry247@gmail.com
  fricanoart@gmail.com
  fruitsale.store@gmail.com
  funnykidcollections@gmail.com
  fuschiarabbit@yahoo.com
  futureofjfab@gmail.com
  fuyifuyiyang@gmail.com
  gabesblahrt@gmail.com
  gabewexler@gmail.com
  gabrahamson11@gmail.com
  gabrielescobedoart@gmail.com
  galadima90@gmail.com
  gallardo.cynthia33@gmail.com
  gallery312art@gmail.com
  gamagerardo@gmail.com
  garbagegals.collective@gmail.com
  gbrlaviles@gmail.com
  gcwaterworks@gmail.com
  gdemilyanne@gmail.com
  genevievelise.art@gmail.com
  geniverdelvoye@gmail.com
  genreless.by.sa.lanea@gmail.com
  geo.ibarra@outlook.com
  geoffvg@vaqueroskate.com
  georgiadominici@gmail.com
  gette@gette.com
  getzenteemental@gmail.com
  gfnxartist@gmail.com
  giamattie601@gmail.com
  gibsongreg85@yahoo.com
  ginger.fierstein@gmail.com
  gingerslonakerart@gmail.com
  giovani_v@yahoo.com
  gisandoval@gmail.com
  gisellelexann@gmail.com
  gjvc@outlook.com
  globersonjordan@gmail.com
  gmancilla01@yahoo.com
  goaskpata@gmail.com
  goghmary@yahoo.com
  gongyuwei.art@gmail.com
  gontiverox@hotmail.com
  gonzalez_tara@yahoo.com
  goodwoodfencingco@gmail.com
  graceloeper0218@gmail.com
  graceyripa@gmail.com
  gracklesghost@gmail.com
  grant1377@gmail.com
  gravitterkaya@gmail.com
  greenemadelined@gmail.com
  greeneyelulu18@gmail.com
  greerlcourtney@gmail.com
  gretchenjr@hotmail.com
  greyerwolfe@gmail.com
  gruveindheart@yahoo.com
  grvonny@yahoo.com
  gseppegg@yahoo.com
  guerrillagaragearts@gmail.com
  gus@slimegames.net
  gutierrezyhoshua@gmail.com
  gwaltsak@gmail.com
  gwebberarts@gmail.com
  hadjindpth@icloud.com
  haitchu@gmail.com
  halcyc98@gmail.com
  haley@haleysart.com
  haleyfonfa@gmail.com
  hanae@hanaeko.com
  hannah.fuller@colorado.edu
  hannahsu.work@gmail.com
  harrison.munden@gmail.com
  harrisserena@yahoo.com
  harryholiday2020@gmail.com
  hatemail.design@gmail.com
  hathi.swati@gmail.com
  haya.ah@gmail.com
  hayilaaliyah12@gmail.com
  hayyleyy@icloud.com
  hazel.quintanilla82@gmail.com
  hazelpybispotter@hotmail.co.uk
  heartvoskanyan@gmail.com
  heikogreb1@hotmail.com
  heinzabari@yahoo.com
  hellapizza24@gmail.com
  hello@brandonhodges.art
  hello@britvaldez.studio
  hello@dianaburman.com
  hello@iamrobart.com
  hello@koseligclub.com
  hello@languageofknots.com
  hello@lobstertee.com
  hello@mnkychau.com
  hello@theresahongart.com
  hello@xycaestello.com
  helloarielliu@gmail.com
  hernandez.jvr1@gmail.com
  herreraliliana1@gmail.com
  hessjohnstonart@gmail.com
  hfreinkel@yahoo.com
  hi@coy-media.com
  hi@shaneheath.com
  hiddenbyart@gmail.com
  highethics@hotmail.com
  hinton24@gmail.com
  holleyd130@gmail.com
  hollidougan@gmail.com
  holly0720@hotmail.com
  holmesdemarco@yahoo.com
  hondabro90@gmail.com
  hoot.hooting@gmail.com
  howdyhatbarmke@gmail.com
  howgirlsdospace@icloud.com
  hromdhane97@gmail.com
  hsinndy@gmail.com
  huckwirtz@gmail.com
  hugomeat19@gmail.com
  hush.mouse@gmail.com
  hw.jonart@gmail.com
  hwilliamswj@gmail.com
  hybimb5@gmail.com
  i.cree.8.u@gmail.com
  iamdaily365@gmail.com
  iamnai84@gmail.com
  iamnikolai@comcast.net
  iankuikedia9@gmail.com
  ignatiuslinde@gmail.com
  igor.mordatch@gmail.com
  ilgassq@gmail.com
  illuminatingworld.mykael@gmail.com
  ilsechangita415@gmail.com
  imagesby.bjeane@gmail.com
  imalang@me.com
  indigenousluxuryco@gmail.com
  infinitementality10@gmail.com
  info.manikasf@gmail.com
  info@andreavalentini.com
  info@aquamooncosmos.com
  info@artkriminal.com
  info@bandbtees.com
  info@emmacheng.com
  info@jessboldt.com
  info@johnbucklin.com
  info@lebohemianmuse.com
  info@machinaxart.com
  info@oakandmooncandles.com
  info@pancakesandbooze.com
  info@proudstutter.com
  info@ronindecals.com
  info@rossimissionsf.com
  info@sforsparkle.com
  info@tiedbythesea.com
  inked1970@aol.com
  inkyfingersprintshop@gmail.com
  inkzilla1@gmail.com
  inquiries@villainousjess.com
  iparatore@gmail.com
  irisspathe@gmail.com
  irisyu808@gmail.com
  isaaclee9759@gmail.com
  isabel.j.dow@gmail.com
  isabelchua86@gmail.com
  isabellaschlosberg@icloud.com
  isaiah.mark.phillips@gmail.com
  isaiahb321@gmail.com
  iseager@att.net
  isiahcharms@yahoo.com
  ismaell90@yahoo.com
  isnervision@hotmail.com
  itfeelslikefloating@gmail.com
  itsabird01@gmail.com
  itsmonty@icloud.com
  itykame@gmail.com
  ivanlobas@gmail.com
  ivanrami76@gmail.com
  ivelissegarcia121503@gmail.com
  ivydragonfly@yahoo.com
  ivyswirewrap@gmail.com
  j.cacaohunter@gmail.com
  j.f.intuitveart@gmail.com
  j.mig1982@gmail.com
  jabbati@mac.com
  jacoborlita@gmail.com
  jacobsousa92@gmail.com
  jacovarius@gmail.com
  jacquelinequale@gmail.com
  jaguarcancun@gmail.com
  jalilaabell@gmail.com
  jamie.crutchfield@gmail.com
  jamieleighflaxman@yahoo.com
  jamietaylor510@gmail.com
  jamyeah97@gmail.com
  jan.simmala.art@gmail.com
  jan.simmala@gmail.com
  jankzine@gmail.com
  jaroldcadionart@gmail.com
  jas3ree@gmail.com
  jascanas@yahoo.com
  jasonalvarado1994@gmail.com
  jasonengelund@gmail.com
  jasperfigueroa@gmail.com
  jassverart@gmail.com
  javiarch@yahoo.com
  jay.ro84@yahoo.com
  jazminbrown18@yahoo.com
  jazreyes389@gmail.com
  jazzicalglass@gmail.com
  jbturin@gmail.com
  jc.st2@icloud.com
  jcarrigan7553@gmail.com
  jcoop715@gmail.com
  jdlorentz@gmail.com
  je.artdes@gmail.com
  jeanetteyarte@gmail.com
  jeanne333@sbcglobal.net
  jeanniemarietattoos@gmail.com
  jeff@jeffquiros.com
  jeffjeff065@gmail.com
  jeffreyandrade@yahoo.com
  jefftessmer1984@yahoo.com
  jelena.skracic@gmail.com
  jennylim0309@gmail.com
  jennypuenterocks@gmail.com
  jeremymarcelino@gmail.com
  jerhatcher@gmail.com
  jermainetison@gmail.com
  jess.hutton77@yahoo.com
  jessereyes247@gmail.com
  jessesrj98@gmail.com
  jessicachristinewilliams@yahoo.com
  jessicadotwinter@gmail.com
  jessicamarieflores@gmail.com
  jessicapederson6@gmail.com
  jessicapeluffo94@gmail.com
  jesus.cristian.gutierrez@outlook.com
  jg.jennigrant@gmail.com
  jgljr.86@gmail.com
  jha.rashmi101@gmail.com
  jherren1@gmail.com
  jilliannsilva@gmail.com
  jillpatterson95@gmail.com
  jim@rawideaphotography.com
  jimmymcintosh5@gmail.com
  jinal.shah.design@gmail.com
  jingrace@stanford.edu
  jjincjoh@yahoo.com
  jjlljj32725@gmail.com
  jjoya7190@gmail.com
  jk@sheridonkeithdesign.com
  jlacap@gmail.com
  jlichnovsky@mac.com
  jlllc.lejon@gmail.com
  jmartell095@gmail.com
  jmazzei11@yahoo.com
  jmherbst06@gmail.com
  jmmedina768@gmail.com
  joakingdom@yahoo.com
  joe_dan01@yahoo.com
  joeander29@gmail.com
  joekimble@ymail.com
  joelmillikan@gmail.com
  joeypainter3@gmail.com
  john.johnlr@gmail.com
  john@twobaldguysart.com
  johndepianto@gmail.com
  johnneuhoff@gmail.com
  johnnydubb23@gmail.com
  johnsonshawn378@gmail.com
  johnwhitmarshsf@gmail.com
  jojoleelynn15@gmail.com
  jomairestudio@gmail.com
  jonahsart@gmail.com
  jonathandemers17@gmail.com
  jonathanreesegoldie@gmail.com
  jones.laurenb@gmail.com
  jonesy4u@gmail.com
  jonnietibbetts8@gmail.com
  jonny.popovich@gmail.com
  jonnyisgoode@gmail.com
  jordan20_3@yahoo.com
  jordand718@gmail.com
  jose.m.hernandez17@outlook.com
  jose_felix_castro@yahoo.com
  josegabeangeles@gmail.com
  josepablo244@hotmail.com
  joseph.arruda@gmail.com
  josephwonga2@gmail.com
  joseporras25@gmail.com
  joset_medina@hotmail.com
  josetteseitz@gmail.com
  joshsmothers@gmail.com
  josiepeck415@gmail.com
  joyner.e@gmail.com
  jp.foesad@gmail.com
  jpowell@srcs.org
  jps847@gmail.com
  jqcurtis@me.com
  jrb5786@gmail.com
  jrstokes517@gmail.com
  jsebcosta@gmail.com
  jshepherd916@gmail.com
  jsiuzmuidzinas0@gmail.com
  jsmaldonadoarte@gmail.com
  jsphrodriguez75@gmail.com
  jtfaraji@gmail.com
  ju26ne@gmail.com
  jucuvee@gmail.com
  juliajasminesjewels@gmail.com
  juliana.s.galeotti@hotmail.com
  juliandemark@gmail.com
  juliawarthin@yahoo.com
  julieabi@gmail.com
  julieforbush13@gmail.com
  julio.o.art@gmail.com
  junara@yahoo.com
  just1justin510@gmail.com
  justgbrow@gmail.com
  justin@pancakesandbooze.com
  justinbarreras@yahoo.com
  justingallen@me.com
  justinpattonart@gmail.com
  justinwrightpaints@gmail.com
  jwhistler0325@gmail.com
  k.cowan@att.net
  k@kabuay.com
  kaceydominguez@gmail.com
  kageuniversal11@gmail.com
  kaikootattoo@gmail.com
  kaiyah1230@gmail.com
  kaknox7@aol.com
  kalaniware.art@gmail.com
  kalaoui2014@gmail.com
  kanghsiong@gmail.com
  karalaurel73@gmail.com
  karamarsonart@gmail.com
  karen@bellakruse.com
  karli.renken@gmail.com
  karlo.henry.velazquez@gmail.com
  karlottaloves@hotmail.com
  karmabrooks.kb@gmail.com
  karmastormy73@gmail.com
  kaseyarrington@icloud.com
  katawesome5000@gmail.com
  katayoonhemati@gmail.com
  katdodge22@yahoo.com
  kateebrown790@gmail.com
  katependergrass11@gmail.com
  katereboli@gmail.com
  katevefosse@gmail.com
  katewcarlin@gmail.com
  kath.james96@gmail.com
  kathleen.storts@gmail.com
  katie.santiago1200@gmail.com
  kayleesalas7@gmail.com
  kayspsychedelia@gmail.com
  kbarnett81@gmail.com
  kbrowne2@yahoo.com
  kclay90@gmail.com
  kctaylor4287@gmail.com
  keck.quinn@gmail.com
  keena.cardak@sephora.com
  keeshaun96@gmail.com
  keithf33@gmail.com
  kelcihartz@gmail.com
  kellyjeancasmey@gmail.com
  kellykloud77@gmail.com
  kelsey.rogers.lpt@gmail.com
  kelty.babeross@gmail.com
  kemurcia34@gmail.com
  kenna244@hotmail.com
  kenzienoelleart@yahoo.com
  kerihughesart@gmail.com
  keripowell@live.com
  kerriaengelder@gmail.com
  kerriganhaleya@gmail.com
  kessien.art@gmail.com
  kevinemerica@live.com
  kevinjosephjuan@gmail.com
  kevinkoza@gmail.com
  kfreshj@gmail.com
  khalishchafiq@gmail.com
  khanzaali@gmail.com
  kidraptor49@yahoo.com
  kieran@paracosmimages.com
  kieshaheals@gmail.com
  kiloskomics@gmail.com
  kimberlydodgeart@gmail.com
  kimboleee@gmail.com
  kimwanart@yahoo.com
  kipwesterfield@gmail.com
  kishyrubygunjan@gmail.com
  kjara415@hotmail.com
  kkapanets@yahoo.com
  kkra13@yahoo.com
  klewisphotoventures@gmail.com
  klubbhouseentertainment@gmail.com
  kmsz2810@gmail.com
  knickjim@gmail.com
  knyrssll24@gmail.com
  koharrow10@gmail.com
  komashchenko@gmail.com
  konstantinesoldatos@gmail.com
  kozispoon@gmail.com
  kplenzphotography@gmail.com
  kristellioswald@gmail.com
  kristens.arts@gmail.com
  kristi@kristicoronado.com
  kristian3t8smith@gmail.com
  kristine@kmooreart.com
  kroma03@gmail.com
  kromatikasf@gmail.com
  krudxscubensi@gmail.com
  kskin69@gmail.com
  kukoomob@gmail.com
  kurrline@gmail.com
  kyartmek@gmail.com
  kyle.blaquiere@gmail.com
  kyraanastasiak@gmail.com
  l@lolareed.com
  l_rivera77@yahoo.com
  lacknerkurteric@gmail.com
  ladamalunashop@gmail.com
  ladiggs21@gmail.com
  lafonda00@hotmail.com
  laiberryart@gmail.com
  lamarrsart@gmail.com
  langlewa@gmail.com
  larkc@me.com
  lastwishontheplaya@gmail.com
  latintafmg@gmail.com
  lauragrdesigns@yahoo.com
  laurameisenegreen@gmail.com
  lauravespertine@gmail.com
  laureleena@gmail.com
  lauren.k.prince@gmail.com
  laurenjohnsonmuralist@gmail.com
  laurenkm15@gmail.com
  lauriemsedwards@gmail.com
  lavenderelic@gmail.com
  lavidaesmagia92@hotmail.com
  laya.cooperman@gmail.com
  laylaskramstad@yahoo.com
  lbedal2@gmail.com
  lcorrie1561@gmail.com
  leannalagpacan@gmail.com
  leena.janmohamed@gmail.com
  legreeneartstudios@gmail.com
  lehconcept@gmail.com
  lelandthemains@gmail.com
  lenawing91@gmail.com
  lenzlady2002@yahoo.com
  leosensations@gmail.com
  lepunkieshop@gmail.com
  lesketchbog@gmail.com
  leslieledesma6@gmail.com
  lestoil@comcast.net
  lewtealew@gmail.com
  leyla.nobatova.art@gmail.com
  lgmallojr@gmail.com
  lhirata_83@yahoo.com
  liamskye@gmail.com
  lian.yung.58@gmail.com
  lianecarter@yahoo.com
  lianne.running@gmail.com
  liannedias90@gmail.com
  lifes_odd@yahoo.com
  lifvendahl@aol.com
  lightninganddiamonds@gmail.com
  lightologie@gmail.com
  likhaco2@gmail.com
  lilcactusbabies@gmail.com
  lilgamerdane@gmail.com
  lily_rodriguez@pacbell.net
  lilymarylander@gmail.com
  limitlessxdreams@gmail.com
  linahsofi@gmail.com
  lindalingren@me.com
  lindavision.sf@gmail.com
  lindsaylangsdale@gmail.com
  lindsaystickney@gmail.com
  linzy.miggantz@gmail.com
  lisa.valle@gmail.com
  littlehairguru@gmail.com
  livegood.4us@gmail.com
  lizboeder@gmail.com
  lizvpottery@gmail.com
  lizzikresteller@gmail.com
  lizzywschneider@gmail.com
  ljdurand@sbcglobal.net
  lmbolger@gmail.com
  lmoniquedesigns@gmail.com
  lnrosenberger@gmail.com
  loadashwin@gmail.com
  loaris95@gmail.com
  login@nyxa.co
  lonimarie005@gmail.com
  lopezfearless8@gmail.com
  lorena.guirgis@yahoo.com
  lorilou72@hotmail.com
  losespirituscollective@gmail.com
  lostinsafeway@gmail.com
  louixellem.art@gmail.com
  lrkreations1@gmail.com
  lucasgraham181@gmail.com
  lucasm2014@hotmail.com
  luciam.artwork@gmail.com
  lucidfluidsartwork@gmail.com
  lucyborden1997@gmail.com
  luismayanman@gmail.com
  lukamaru.art@gmail.com
  lukeandahazy@gmail.com
  lululwalsh@gmail.com
  lumpartsf@gmail.com
  lunatechdesign@gmail.com
  luperekm@gmail.com
  lusciousproductsco@gmail.com
  lxseto93@gmail.com
  lychamestudios@gmail.com
  lydiacleverley@yahoo.com
  lydiawood131@gmail.com
  lylamerle@gmail.com
  lynnmgustafson@gmail.com
  m.degrado@hotmail.com
  m.harrisemployment@gmail.com
  m@zenstatetouch.com
  mackenzie_noelle@yahoo.com
  macme25@hotmail.com
  macy.hembd@gmail.com
  madattheartist@gmail.com
  made@trebeyond.com
  madeinchinaart@gmail.com
  madisella27@gmail.com
  madison.nicole.peterson@gmail.com
  maeblackmoreart@gmail.com
  maeday1089@gmail.com
  magdalene.arts.contact@gmail.com
  maggieahmann@gmail.com
  mahi.daris.poems@gmail.com
  maigarlicnoodles@gmail.com
  mail@katia-goa.com
  mail@krystallauk.com
  mail@rachelreinfurt.com
  mail@violabevziuk.com
  mailavijit@gmail.com
  mailechrist@aol.com
  maimaiyours@gmail.com
  majesticmooncandlecompany@gmail.com
  makikoharris@gmail.com
  makunts@gmail.com
  malachidarthur@gmail.com
  malhawagri@icloud.com
  malibu_mermaid@hotmail.com
  malisa.suchanya@gmail.com
  malisbee76@gmail.com
  manadkk@gmail.com
  manasa.karthikeyan@gmail.com
  mantra9@gmail.com
  maraleabrown@gmail.com
  marc@warningkick.com
  marcallen0125@gmail.com
  marconicalindas@yahoo.com
  marcus.gonzalez12@gmail.com
  marcus_lowery22@yahoo.com
  mariaguzman@gmail.com
  mariah.g13@yahoo.com
  marian.warner405@gmail.com
  marianne06stella@gmail.com
  marieloucifuentes@hotmail.com
  marina7758@yahoo.com
  marinah@cca.edu
  marissamuller9@gmail.com
  marlibeetf@gmail.com
  marusja.sf@gmail.com
  marvinpantaleon92@gmail.com
  marvis.jarvis@gmail.com
  marynaeme@gmail.com
  mashatyomkina@gmail.com
  masmas8687@gmail.com
  masonmonty@hotmail.com
  matb4067@gmail.com
  mathewbarnesart@gmail.com
  mattbergart@gmail.com
  matteodavincimngmt@gmail.com
  mattford50@gmail.com
  matthewcmooney@gmail.com
  matthewh160@hotmail.com
  mattmilanoart@gmail.com
  max4mkt@gmail.com
  maxim.krikun@gmail.com
  maxnaff@gmail.com
  maxtondramite@comcast.net
  maytalgot@gmail.com
  mayzie.zechini@ousd.org
  mcgowenlakisha@outlook.com
  mcleodkaeli@gmail.com
  mdirito@pacbell.net
  mdstudios96@gmail.com
  me2534@aol.com
  meehaun.wade@gmail.com
  megals123@gmail.com
  megan@rosenoirstudio.com
  meganmakesthings98@gmail.com
  megshayart@gmail.com
  mehakbansil@gmail.com
  mekagirard@gmail.com
  melanie.sangalang@gmail.com
  melek7oman@gmail.com
  melissaayr@gmail.com
  melissakelch@gmail.com
  mellewood50@gmail.com
  melody_idakaar@yahoo.com
  melodyshaiken@gmail.com
  melodyzea@gmail.com
  memo4mck@gmail.com
  meshellwah@gmail.com
  meztli.sanchez@yahoo.com
  mgalvan.art@gmail.com
  mgermger@yahoo.com
  mgilp001@ucr.edu
  mgminicozzi@gmail.com
  mia_casino@yahoo.com
  miazcreations1111@gmail.com
  micaelacornwall@gmail.com
  micgri@gmail.com
  michael.chung.2014@gmail.com
  michael.simons75@yahoo.com
  michaela.rose.visuals@gmail.com
  michaelangelo.atencio@gmail.com
  michaelleecroft@gmail.com
  michaelmarquez11@gmail.com
  michellebehan20@gmail.com
  michellebutchko@gmail.com
  michelleisabelle22@hotmail.com
  michellekimber@gmail.com
  microgallerysf@gmail.com
  mie.bak.larsen@gmail.com
  miguel1018@yahoo.com
  mikecheema@gmail.com
  mikeisart@me.com
  mikeisrude@gmail.com
  mikepcreative@gmail.com
  mikkelsenheather@gmail.com
  milanocre84@gmail.com
  milkacrafter@gmail.com
  millie.rae.art@gmail.com
  miraculoussun@gmail.com
  miss_jo_anns@yahoo.com
  missannabaker@gmail.com
  missbeeautiful@icloud.com
  missionarte@gmail.com
  mk.etemadi@gmail.com
  mkauber0@gmail.com
  mkeylor@gmail.com
  mkramer011@gmail.com
  mlachance.art@gmail.com
  mleahart@gmail.com
  mlhernandez415@gmail.com
  mndozaart@gmail.com
  mo.ramirez3@gmail.com
  monicasolis2121@gmail.com
  monroecreative@gmail.com
  mookiefink@gmail.com
  moonstonesf@gmail.com
  moorebrentjohn@gmail.com
  moxiejuju@gmail.com
  mperez424@gmail.com
  mr.poopypantsman@gmail.com
  mriley0730@gmail.com
  mrod8182@gmail.com
  mrpinstripe@gmail.com
  ms_stardust@yahoo.com
  msheryl_r@hotmail.com
  msupreme75@yahoo.com
  mteresa.p@gmail.com
  myc420@gmail.com
  mzphatpockets@gmail.com
  n.jarabek@gmail.com
  naijahmoody@gmail.com
  nakiachapman@gmail.com
  nancymoralewis@gmail.com
  nancynfloyd@gmail.com
  naomileafs@gmail.com
  natalie@natalieora.art
  nataliecorvino@gmail.com
  natalieforsberg@gmail.com
  natanyakramer@gmail.com
  nateakings@gmail.com
  nathanielcalles@gmail.com
  nattynarwhal@gmail.com
  nauticalnat.art@gmail.com
  navid.bozorgzad@gmail.com
  ncraig1@live.com
  nea.mcpherson@gmail.com
  nealloganart@gmail.com
  neonaesv@gmail.com
  nerdgoat@icloud.com
  nftcomp@gmail.com
  nicolecortez.design@gmail.com
  nicoleduvall.art@gmail.com
  niebrown@gmail.com
  nightskyarts@comcast.net
  nikkilafave@gmail.com
  nikkivickery@icloud.com
  ninaamberg@yahoo.com
  ninabaeza@gmail.com
  nitacornelio86@gmail.com
  njmendoza@yahoo.com
  nkohart@gmail.com
  nms.artist@gmail.com
  noa.s.rose@gmail.com
  noahalexanderheinz@gmail.com
  noemimakesthings@gmail.com
  noori@nooriart.com
  nordstromanna@gmail.com
  normanthelion@gmail.com
  np.arts@yahoo.com
  nrobless@gmail.com
  nuanceart@gmail.com
  o.p.art415@gmail.com
  obianujuoma@gmail.com
  ochsenfeld.mich@gmail.com
  odessaclark0@gmail.com
  officinazero@gmail.com
  ofgoldandthread@gmail.com
  ofilledegrace@gmail.com
  ohana.goods@gmail.com
  oilpainting62@gmail.com
  okayreinhard@gmail.com
  ola.lindqvist@live.com
  omayra.r.robles@gmail.com
  omolade.tomi@gmail.com
  orangeislandstudio@gmail.com
  orowitz@gmail.com
  oscarartist2018@gmail.com
  oscarhuerta619@gmail.com
  oscarrobinson911@gmail.com
  outerspacegarage@gmail.com
  ouwerkerkg@gmail.com
  owendanielcolors@gmail.com
  ownthecolor@gmail.com
  ozzmosis415@gmail.com
  p3droz@yahoo.com
  pacquiaophotography@gmail.com
  paigeyann99@gmail.com
  paintingforthefuture@gmail.com
  pamela.schillaci@gmail.com
  pamelashoaf@gmail.com
  pandalicious415@gmail.com
  pandamonion@gmail.com
  papercliphangup@gmail.com
  pat.m.art@gmail.com
  patrickwalsh17@gmail.com
  patojas415@gmail.com
  pattichong2@gmail.com
  paultracy5@gmail.com
  paultschudi@yahoo.com
  pb.arts@hotmail.com
  pburns415@gmail.com
  pedregon.nolan@gmail.com
  periwinklepixie@hotmail.com
  perla.artistry1990@gmail.com
  peterchung92@icloud.com
  phatlicioustreasures@yahoo.com
  philbailey312@gmail.com
  philomenawoodward@gmail.com
  photobyrein@gmail.com
  pianuart@gmail.com
  pinchyclaw@gmail.com
  pink_rebel_yell@yahoo.com
  pixelsandpearls@gmail.com
  plaidowlcreations@gmail.com
  plantmexicano@gmail.com
  pliskovskiy@icloud.com
  poc.artists@gmail.com
  poetrypeacock@gmail.com
  pointer.art@protonmail.com
  preetpalsingh@live.com
  prestidigitationproduction@gmail.com
  prettyfreakystudio@gmail.com
  prima_materia@yahoo.com
  priscillap24@gmail.com
  prismsandprisoners@gmail.com
  prodigydestini@gmail.com
  produbzilla@yahoo.com
  puffyhummingbird@gmail.com
  punkrainbowart@gmail.com
  purplekraken@gmail.com
  purposefocused@gmail.com
  qadiramarquette@gmail.com
  quintessentiallyq@gmail.com
  r.barron.art@gmail.com
  rabbitandthehat@gmail.com
  rachelannmason@gmail.com
  rachelbeautymode@yahoo.com
  rachelkayphotography@gmail.com
  rachellefong415@gmail.com
  rachellekuhn@gmail.com
  rachelquintero99@gmail.com
  rafaelreynolds3@yahoo.com
  raffaellasalinas@gmail.com
  ramiropaez415@gmail.com
  ranipalmtree@gmail.com
  raquel.oliveiros@gmail.com
  rashaadmalik@gmail.com
  rawheadstudio@gmail.com
  rayavid@gmail.com
  rcrockenbeck@gmail.com
  rebeccarowe.art@gmail.com
  reesecoleman2@gmail.com
  reg.a.m.h@gmail.com
  reneemoon13@gmail.com
  replicasimone@gmail.com
  rezaghavampour@gmail.com
  rhythmofwriting@gmail.com
  ribeiropereira.rp@gmail.com
  richmartin@mac.com
  rickmuerte@gmail.com
  ricosuavepaints@gmail.com
  rj.yoon@icloud.com
  rjlphotos@gmail.com
  rjosephart@gmail.com
  rjwhalen@gmail.com
  robbiegrayson@gmail.com
  robertsheltonart@gmail.com
  robertzepeda55@yahoo.com
  robin@crookedowlstudio.com
  robindee@lavabit.com
  robpaints@gmail.com
  roccoartwork@gmail.com
  rockstarcreates@gmail.com
  rocoandrews@gmail.com
  roderickbrown1@gmail.com
  rodrigo-g@hotmail.com
  rogerpamintuan415@gmail.com
  romainvintage@gmail.com
  romanrivers@gmail.com
  roninkobayashiart@gmail.com
  rose.ofallon@gmail.com
  roseanntrinidad@gmail.com
  rosemarymonclova@gmail.com
  roshnathaker@gmail.com
  rowan.vp@gmail.com
  rpgranger@gmail.com
  rubenmtz415@gmail.com
  rubyandoak@gmail.com
  runawayrabbit.rb@gmail.com
  rwaddell@alum.mit.edu
  ry.ortiz415@gmail.com
  ryan.e.buckley@gmail.com
  ryanmichealray@gmail.com
  ryans.artistry@gmail.com
  rylawilkerson@gmail.com
  s.e.artist@gmail.com
  sabrinaortizart@gmail.com
  sadiesteelephant@gmail.com
  sailorcrafts@gmail.com
  saiz_nate@hotmail.com
  samanthacabral23@yahoo.com
  samarabelhadj@gmail.com
  samaritanwoman@yahoo.com
  samienation@gmail.com
  sammattes@gmail.com
  samplanning@gmail.com
  sandraflores415@gmail.com
  sandrajleos@yahoo.com
  sarahbeampainting@gmail.com
  sarahmarshall2312@gmail.com
  sarahnlove@gmail.com
  satchelart@gmail.com
  savagex310@gmail.com
  savedbysol@gmail.com
  saylor.heidi@gmail.com
  sbugbee@sbcglobal.net
  scarred.saint@gmail.com
  scottmalinowski@yahoo.com
  screamsapphire@gmail.com
  seabeartattoo@gmail.com
  sealtattoo22@yahoo.com
  searchingforsigns@gmail.com
  sebastiansolanoart@gmail.com
  sennlynne@gmail.com
  serafineandco@gmail.com
  serenity.sews@gmail.com
  shadeytreestudio@gmail.com
  shadowdancer73@yahoo.com
  shailenelayna@gmail.com
  shakeelah.amin@gmail.com
  shameikamay@gmail.com
  shannonmduffy@gmail.com
  shantiarts@gmail.com
  shayla.bellwether@gmail.com
  shaylaspencer@gmail.com
  sheena.ann.art@gmail.com
  shelbzdesigns@gmail.com
  shelly.art.heart@gmail.com
  sher@sherriwooddesigns.com
  shiraevelyn@gmail.com
  shopblkwndr@gmail.com
  si2lent@hotmail.com
  silentroadart@gmail.com
  silverarrowwoman@gmail.com
  simplyalyssa4@gmail.com
  sinoramos@gmail.com
  sirenae@yahoo.com
  sjohnsonstreetart@gmail.com
  sketchinglaura@gmail.com
  sl.anaya@yahoo.com
  slaytonbrown@gmail.com
  sleepingweaselart@gmail.com
  slyguyzdesignz@gmail.com
  smlkandi@gmail.com
  smurphyart@gmail.com
  snailcreep@gmail.com
  sneakytiki@gmail.com
  so.much.garlic@gmail.com
  sokolikova12@gmail.com
  soleil.creates@gmail.com
  sonnysteele01@gmail.com
  sophiaescobedo15@gmail.com
  sophiegreydesigns@gmail.com
  sophiekathrynbendell@gmail.com
  soulmission.art@gmail.com
  sparklesdesignco@gmail.com
  spiritedfeminine@gmail.com
  spookypeonies@gmail.com
  squishblobfish@gmail.com
  srothenberg13@gmail.com
  stadtbauerkatrina@gmail.com
  stardust.sprinkleberry@gmail.com
  starlingstudioco@gmail.com
  staticelectricstudios@gmail.com
  stefanie.olson1993@gmail.com
  stephaniesullivan@gmail.com
  stephcitrus@gmail.com
  sterlingandrews@gmail.com
  stevo.sf@gmail.com
  stinaborger@gmail.com
  stlweb04@gmail.com
  streetpunkphotography@gmail.com
  studio@jacindakowalski.com
  studiosalt@sbcglobal.net
  stuforreal@yahoo.com
  subrosacreative@gmail.com
  sulcristina51@gmail.com
  sunandseedsjewelry@gmail.com
  sunflowerseedphoto@gmail.com
  sunni.danielle5@gmail.com
  sunnyraysart@gmail.com
  sunshine.junglist@gmail.com
  supplysf@gmail.com
  surfingowl@gmail.com
  susanmillerstudio@gmail.com
  svh.arts@gmail.com
  swamp.witch.art@gmail.com
  swellyskins@gmail.com
  t.h.rodriguez.1985@gmail.com
  t.simsek83@gmail.com
  tahoeflute@gmail.com
  talia.t.art@gmail.com
  tamara.s.art@gmail.com
  tanaka.jpeg@gmail.com
  tanyalou14@gmail.com
  tanya_barajas@yahoo.com
  taratorobio@gmail.com
  tattersallartist@gmail.com
  team+testvendor0154@wolfdevelopmentstudio.com
  teeceelives@gmail.com
  teequiem@gmail.com
  teiagustafson@gmail.com
  tenkitten@gmail.com
  terriereunion@gmail.com
  thelordneil@gmail.com
  theloveartist2@gmail.com
  themuralproject@gmail.com
  thenewdadproject@gmail.com
  thepaige@gmail.com
  theresamaechelle@gmail.com
  theuglywolf@gmail.com
  thisisashleyrenee@gmail.com
  thomasauner1@gmail.com
  tigerhqmangement@gmail.com
  tigerx.hq@gmail.com
  tikoyo.art@gmail.com
  timelessvtg@gmail.com
  timigmedia@gmail.com
  tina.art.life@gmail.com
  tindall415@gmail.com
  tinseltreeartco@gmail.com
  tj.beebe@gmail.com
  tkarnold@gmail.com
  toadhouseillustrations@gmail.com
  tomaszwmarcinkiewicz@gmail.com
  torylynnpaints@gmail.com
  traceybates7@gmail.com
  trainworthy@gmail.com
  trinitymarriott143143@gmail.com
  trishan@trishanbee.com
  tropicalmuze@gmail.com
  truth@truthtattoo.com
  tsw37@gmail.com
  tttimeline@gmail.com
  tucsonphoenix99@gmail.com
  tularejordan@gmail.com
  twinpinnies@gmail.com
  typographyproject@gmail.com
  u.cano.art@gmail.com
  uglyshirtcollective@gmail.com
  ulrikke-art@hotmail.com
  unicornscanfly9@gmail.com
  unomaha5@gmail.com
  urbangarden.sf@gmail.com
  ursula.m.garcia@gmail.com
  ux.ling@gmail.com
  v.delosreyes@yahoo.com
  v.reza03@gmail.com
  valeria.aranda88@gmail.com
  valeria4395@gmail.com
  valeriasuniga@gmail.com
  valeriavara94@gmail.com
  vandenbrandtfamily@gmail.com
  varangiangarden@gmail.com
  vatornado@gmail.com
  vb.arts@gmail.com
  velvetfoxapparel@gmail.com
  veramakesart@gmail.com
  vernalequinox@gmail.com
  victoriablackart@gmail.com
  vidyagrace@gmail.com
  vincentasaro@yahoo.com
  violettavoyage@gmail.com
  vipulrajan@gmail.com
  viridiandesign@yahoo.com
  viviannesart@gmail.com
  vkwong78@yahoo.com
  vmeadows0@gmail.com
  voodoocreature@gmail.com
  vuelveporfa@gmail.com
  wackykay@gmail.com
  waldenlindholm@gmail.com
  walesworth@yahoo.com
  wanda.wren@comcast.net
  wardart@live.com
  waysideflowers@gmail.com
  wbernard7@yahoo.com
  weirdworkshops@gmail.com
  wendythebee@gmail.com
  whhunter1001@gmail.com
  whoopitywoo@gmail.com
  whubbard@gmail.com
  wildpoppyink@gmail.com
  williamdelarosa619@gmail.com
  willowriverart@gmail.com
  willyorwonttheywear@gmail.com
  wino_art@yahoo.com
  witcher_theresa@yahoo.com
  wolfpacksurf@yahoo.com
  womb2worldjewels@gmail.com
  woodwardillustration@gmail.com
  workwithkimber@gmail.com
  worldsendstudio@gmail.com
  wrightartists@gmail.com
  wvela1974@yahoo.com
  xchrissyx@gmail.com
  xian.lhote@gmail.com
  xileniasart@gmail.com
  xjbrownie@gmail.com
  xochitllopezart@gmail.com
  xomandoo@gmail.com
  xomaybelline@gmail.com
  xoxocatmom@gmail.com
  yaz.garcia94@gmail.com
  ydiazdiaz@gmail.com
  yehzenia@gmail.com
  yenng@gmail.com
  yeshaoba@gmail.com
  yoga.with.katie@gmail.com
  yogaonlakeave@gmail.com
  yoli.gonzalez@yahoo.com
  yosilverberg@gmail.com
  youngandbrazen@gmail.com
  youngbloodstudio@gmail.com
  yume.by.anna@gmail.com
  yunojoe@gmail.com
  yvesbonnefoy@gmail.com
  z.castillofuentes@gmail.com
  zahranafar68@gmail.com
  zandracraft@gmail.com
  zanelladesign@gmail.com
  zennia@zennia.art
  zfloresart@gmail.com
  zhp.art@gmail.com
  zoecollins415@gmail.com
  zoedesrocher@gmail.com
  zoeellisart@gmail.com
  zoenicoledesigns@gmail.com
  zoraida.paola@gmail.com
  zrleigh@gmail.com
]

applicants = [
  { email: "artaaaheart@gmail.com",         status: "approved", from_invite: true  },
  { email: "artbyadrianam@gmail.com",        status: "approved", from_invite: true  },
  { email: "chelseabrie@gmail.com",          status: "approved", from_invite: true  },
  { email: "colorsofclara@gmail.com",        status: "approved", from_invite: true  },
  { email: "comicauthor.jr@gmail.com",       status: "approved", from_invite: true  },
  { email: "david@shineon.studio",           status: "approved", from_invite: true  },
  { email: "eyezofthagardenzen@gmail.com",   status: "approved", from_invite: true  },
  { email: "goaskpata@gmail.com",            status: "approved", from_invite: true  },
  { email: "graceyripa@gmail.com",           status: "approved", from_invite: true  },
  { email: "gus@slimegames.net",             status: "approved", from_invite: true  },
  { email: "hello@lobstertee.com",           status: "approved", from_invite: true  },
  { email: "ivyswirewrap@gmail.com",         status: "approved", from_invite: true  },
  { email: "jacquelinequale@gmail.com",      status: "approved", from_invite: true  },
  { email: "katewcarlin@gmail.com",          status: "approved", from_invite: true  },
  { email: "kfreshj@gmail.com",             status: "approved", from_invite: true  },
  { email: "lavenderelic@gmail.com",         status: "approved", from_invite: true  },
  { email: "lelandthemains@gmail.com",       status: "approved", from_invite: true  },
  { email: "smlkandi@gmail.com",             status: "approved", from_invite: true  },
  { email: "sulcristina51@gmail.com",        status: "approved", from_invite: true  },
  { email: "tanaka.jpeg@gmail.com",          status: "approved", from_invite: true  },
  { email: "trinitymarriott143143@gmail.com",status: "approved", from_invite: true  },
  { email: "yeshaoba@gmail.com",             status: "approved", from_invite: true  },
  { email: "zahranafar68@gmail.com",         status: "approved", from_invite: true  },
  { email: "zennia@zennia.art",              status: "approved", from_invite: true  },
  { email: "greerlcourtney@gmail.com",       status: "pending",  from_invite: true  },
  { email: "lenzlady2002@yahoo.com",         status: "pending",  from_invite: true  },
  { email: "matteodavincimngmt@gmail.com",   status: "pending",  from_invite: true  },
  { email: "xxnoangelxx@mail.ru",            status: "pending",  from_invite: true  },
  { email: "abstronautics@gmail.com",        status: "approved", from_invite: false },
  { email: "aidinmassoudi@gmail.com",        status: "approved", from_invite: false },
  { email: "annabellripon@gmail.com",        status: "approved", from_invite: false },
  { email: "avcoiffeur@gmail.com",           status: "approved", from_invite: false },
  { email: "bellaleggero@gmail.com",         status: "approved", from_invite: false },
  { email: "chadlight@comcast.net",          status: "approved", from_invite: false },
  { email: "checkmein2027@gmail.com",        status: "approved", from_invite: false },
  { email: "craftyvoyages@gmail.com",        status: "approved", from_invite: false },
  { email: "delovedemetrius@gmail.com",      status: "approved", from_invite: false },
  { email: "deweysgarden@gmail.com",         status: "approved", from_invite: false },
  { email: "domesboff@hotmail.col",          status: "approved", from_invite: false },
  { email: "eaglinchadwick@gmail.com",       status: "approved", from_invite: false },
  { email: "ejrojas89@yahoo.com",            status: "approved", from_invite: false },
  { email: "georgegarcia137@gmail.com",      status: "approved", from_invite: false },
  { email: "hello@crystalcolletterose.com",  status: "approved", from_invite: false },
  { email: "hello@emeudolph.com",            status: "approved", from_invite: false },
  { email: "j.cordy123@gmail.com",           status: "approved", from_invite: false },
  { email: "jackiepriola13@gmail.com",       status: "approved", from_invite: false },
  { email: "jaipetch.bell@gmail.com",        status: "approved", from_invite: false },
  { email: "jaleceiamcdaniel@gmail.com",     status: "approved", from_invite: false },
  { email: "jcloptonfoster@gmail.com",       status: "approved", from_invite: false },
  { email: "josephforbes@outlook.com",       status: "approved", from_invite: false },
  { email: "juliannfloraart@gmail.com",      status: "approved", from_invite: false },
  { email: "kaylavankoll15@gmail.com",       status: "approved", from_invite: false },
  { email: "lucykuo@ymail.com",              status: "approved", from_invite: false },
  { email: "lynnleedesigns19@gmail.com",     status: "approved", from_invite: false },
  { email: "mesperanzam510@gmail.com",       status: "approved", from_invite: false },
  { email: "michaela.flores16@gmail.com",    status: "approved", from_invite: false },
  { email: "neajahbrown@gmail.com",          status: "approved", from_invite: false },
  { email: "peacefulclaycreations@gmail.com",status: "approved", from_invite: false },
  { email: "plugplayhouse@outlook.com",      status: "approved", from_invite: false },
  { email: "schnurrjulia22@gmail.com",       status: "approved", from_invite: false },
  { email: "shmackrealm@gmail.com",          status: "approved", from_invite: false },
  { email: "tail5lid3@gmail.com",            status: "approved", from_invite: false },
  { email: "tonyulloa79@gmail.com",          status: "approved", from_invite: false },
  { email: "ursala29@gmail.com",             status: "approved", from_invite: false },
  { email: "cicilu309@gmail.com",            status: "pending",  from_invite: false },
  { email: "cyiexist4301@yahoo.com",         status: "pending",  from_invite: false },
  { email: "eliackazemi@gmail.com",          status: "pending",  from_invite: false },
  { email: "grace.cookstobn@gmail.com",      status: "pending",  from_invite: false },
  { email: "jamesmarriott143143@gmail.com",  status: "pending",  from_invite: false },
  { email: "jayissk8rdie@gmail.com",         status: "pending",  from_invite: false },
  { email: "mkurimsk@gmail.com",             status: "pending",  from_invite: false },
  { email: "mmarielca@gmail.com",            status: "pending",  from_invite: false },
  { email: "ora@natalieora.art",             status: "pending",  from_invite: false },
]

invitations = {}
inv_ok = 0
inv_fail = 0

invited_emails.each do |email|
  begin
    contact = VendorContact.create!(
      organization: org,
      name:         email.split("@").first,
      email:        email,
      status:       "new",
      contact_type: "lead"
    )
    inv = EventInvitation.create!(
      event:          event,
      vendor_contact: contact,
      status:         "sent"
    )
    invitations[email] = inv
    inv_ok += 1
  rescue => e
    puts "FAIL invite #{email}: #{e.message}"
    inv_fail += 1
  end
end

puts "Invitations: #{inv_ok} created, #{inv_fail} failed"

reg_ok = 0
reg_fail = 0

applicants.each do |row|
  begin
    inv = row[:from_invite] ? invitations[row[:email]] : nil
    r = Registration.new(
      event:              event,
      vendor_application: artists_app,
      event_invitation:   inv,
      email:              row[:email],
      name:               row[:email].split("@").first,
      business_name:      row[:email].split("@").first,
      vendor_category:    "Artists",
      status:             row[:status],
      payment_status:     "pending"
    )
    if r.save
      puts "OK [#{row[:status]}] #{row[:email]}"
      reg_ok += 1
    else
      puts "FAIL #{row[:email]}: #{r.errors.full_messages}"
      reg_fail += 1
    end
  rescue => e
    puts "FAIL #{row[:email]}: #{e.message}"
    reg_fail += 1
  end
end

puts "Registrations: #{reg_ok} created, #{reg_fail} failed"

Registration.set_callback(:create, :after, :send_confirmation_email)
Registration.set_callback(:update, :after, :send_status_update_email)

puts ""
puts "EventInvitations: #{event.event_invitations.count}  (expected 2149)"
puts "Registrations:    #{event.registrations.count}  (expected 73)"
puts "  approved:       #{event.registrations.where(status: 'approved').count}  (expected 60)"
puts "  pending:        #{event.registrations.where(status: 'pending').count}  (expected 13)"
